// Lucide icons referenced by name in the design and data files. Brand glyphs removed from
// lucide-react (Instagram, LinkedIn) are drawn inline with the original Lucide paths.
import type {LucideIcon} from 'lucide-react';
import {AlertCircle,AlertTriangle,ArrowRight,ArrowUpRight,AudioLines,BarChart3,BedDouble,BellRing,Bike,BookOpen,Boxes,Briefcase,Building,Building2,Cake,Calculator,Calendar,CalendarCheck,CalendarClock,CalendarDays,Camera,Check,CheckCheck,CheckCircle2,CheckSquare,ChevronDown,ChevronLeft,ClipboardList,Code2,Compass,ConciergeBell,Factory,FileBarChart,FileCheck2,FileScan,FileSignature,FileSpreadsheet,FileText,Filter,GitBranch,Globe2,GraduationCap,HardHat,Hash,Headphones,HeartPulse,Home,Image,Inbox,Key,Languages,Layers,Library,LineChart,ListChecks,Lock,Mail,Map,MapPin,Megaphone,Menu,MessageCircle,MessageSquare,MessageSquareText,MoonStar,Navigation,Notebook,NotebookPen,Package,Pause,PenLine,PenTool,Phone,PhoneCall,PhoneIncoming,Play,Plug,PlugZap,Plus,Quote,Radar,Receipt,Rocket,Route,Scale,ScanLine,School,Search,Send,Settings2,Share2,ShieldCheck,ShoppingBag,ShoppingCart,SlidersHorizontal,Star,Stethoscope,Table2,TrendingUp,Truck,UserCheck,UserRound,UserSearch,Users,Utensils,Video,Workflow,Wrench,X} from 'lucide-react';

const icons:Record<string,LucideIcon>={"alert-circle":AlertCircle,"alert-triangle":AlertTriangle,"arrow-right":ArrowRight,"arrow-up-right":ArrowUpRight,"audio-lines":AudioLines,"bar-chart-3":BarChart3,"bed-double":BedDouble,"bell-ring":BellRing,"bike":Bike,"book-open":BookOpen,"boxes":Boxes,"briefcase":Briefcase,"building":Building,"building-2":Building2,"cake":Cake,"calculator":Calculator,"calendar":Calendar,"calendar-check":CalendarCheck,"calendar-clock":CalendarClock,"calendar-days":CalendarDays,"camera":Camera,"check":Check,"check-check":CheckCheck,"check-circle-2":CheckCircle2,"check-square":CheckSquare,"chevron-down":ChevronDown,"chevron-left":ChevronLeft,"clipboard-list":ClipboardList,"code-2":Code2,"compass":Compass,"concierge-bell":ConciergeBell,"factory":Factory,"file-bar-chart":FileBarChart,"file-check-2":FileCheck2,"file-scan":FileScan,"file-signature":FileSignature,"file-spreadsheet":FileSpreadsheet,"file-text":FileText,"filter":Filter,"git-branch":GitBranch,"globe-2":Globe2,"graduation-cap":GraduationCap,"hard-hat":HardHat,"hash":Hash,"headphones":Headphones,"heart-pulse":HeartPulse,"home":Home,"image":Image,"inbox":Inbox,"key":Key,"languages":Languages,"layers":Layers,"library":Library,"line-chart":LineChart,"list-checks":ListChecks,"lock":Lock,"mail":Mail,"map":Map,"map-pin":MapPin,"megaphone":Megaphone,"menu":Menu,"message-circle":MessageCircle,"message-square":MessageSquare,"message-square-text":MessageSquareText,"moon-star":MoonStar,"navigation":Navigation,"notebook":Notebook,"notebook-pen":NotebookPen,"package":Package,"pause":Pause,"pen-line":PenLine,"pen-tool":PenTool,"phone":Phone,"phone-call":PhoneCall,"phone-incoming":PhoneIncoming,"play":Play,"plug":Plug,"plug-zap":PlugZap,"plus":Plus,"quote":Quote,"radar":Radar,"receipt":Receipt,"rocket":Rocket,"route":Route,"scale":Scale,"scan-line":ScanLine,"school":School,"search":Search,"send":Send,"settings-2":Settings2,"share-2":Share2,"shield-check":ShieldCheck,"shopping-bag":ShoppingBag,"shopping-cart":ShoppingCart,"sliders-horizontal":SlidersHorizontal,"star":Star,"stethoscope":Stethoscope,"table-2":Table2,"trending-up":TrendingUp,"truck":Truck,"user-check":UserCheck,"user-round":UserRound,"user-search":UserSearch,"users":Users,"utensils":Utensils,"video":Video,"workflow":Workflow,"wrench":Wrench,"x":X};

type Props={name:string;size?:number;className?:string};
export function Icon({name,size=24,className}:Props){
 if(name==='instagram')return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" className={className}><rect x="2" y="2" width="20" height="20" rx="5"/><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"/><line x1="17.5" x2="17.51" y1="6.5" y2="6.5"/></svg>;
 if(name==='linkedin')return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" className={className}><path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z"/><rect width="4" height="12" x="2" y="9"/><circle cx="4" cy="4" r="2"/></svg>;
 const C=icons[name]||Layers;
 return <C size={size} aria-hidden="true" focusable="false" className={className} style={{display:'block',flexShrink:0}}/>;
}
