// Lucide icons referenced by name in the design and data files. Brand glyphs removed from
// lucide-react (Instagram, LinkedIn) are drawn inline with the original Lucide paths.
import type {LucideIcon} from 'lucide-react';
import {Target,Wallet,Handshake,AlertCircle,AlertTriangle,ArrowLeft,ArrowRight,ArrowUpRight,AudioLines,BarChart3,BedDouble,BellRing,Bike,BookOpen,Boxes,Briefcase,Building,Building2,Cake,Calculator,Calendar,CalendarCheck,CalendarClock,CalendarDays,Camera,Check,CheckCheck,CheckCircle2,CheckSquare,ChevronDown,ChevronLeft,ClipboardList,Code2,Compass,ConciergeBell,Factory,FileBarChart,FileCheck2,FileScan,FileSignature,FileSpreadsheet,FileText,Filter,GitBranch,Globe2,GraduationCap,HardHat,Hash,Headphones,HeartPulse,Home,Image,Inbox,Key,Languages,Layers,Library,LineChart,ListChecks,Lock,Mail,Map,MapPin,Megaphone,Menu,MessageCircle,MessageSquare,MessageSquareText,MoonStar,Navigation,Notebook,NotebookPen,Package,Pause,PenLine,PenTool,Phone,PhoneCall,PhoneIncoming,Play,Plug,PlugZap,Plus,Quote,Radar,Receipt,Rocket,Route,Scale,ScanLine,School,Search,Send,Settings2,Share2,ShieldCheck,ShoppingBag,ShoppingCart,SlidersHorizontal,Star,Stethoscope,Table2,TrendingUp,Truck,UserCheck,UserRound,UserSearch,Users,Utensils,Video,Workflow,Wrench,X} from 'lucide-react';

const icons:Record<string,LucideIcon>={"target":Target,"wallet":Wallet,"handshake":Handshake,"alert-circle":AlertCircle,"alert-triangle":AlertTriangle,"arrow-left":ArrowLeft,"arrow-right":ArrowRight,"arrow-up-right":ArrowUpRight,"audio-lines":AudioLines,"bar-chart-3":BarChart3,"bed-double":BedDouble,"bell-ring":BellRing,"bike":Bike,"book-open":BookOpen,"boxes":Boxes,"briefcase":Briefcase,"building":Building,"building-2":Building2,"cake":Cake,"calculator":Calculator,"calendar":Calendar,"calendar-check":CalendarCheck,"calendar-clock":CalendarClock,"calendar-days":CalendarDays,"camera":Camera,"check":Check,"check-check":CheckCheck,"check-circle-2":CheckCircle2,"check-square":CheckSquare,"chevron-down":ChevronDown,"chevron-left":ChevronLeft,"clipboard-list":ClipboardList,"code-2":Code2,"compass":Compass,"concierge-bell":ConciergeBell,"factory":Factory,"file-bar-chart":FileBarChart,"file-check-2":FileCheck2,"file-scan":FileScan,"file-signature":FileSignature,"file-spreadsheet":FileSpreadsheet,"file-text":FileText,"filter":Filter,"git-branch":GitBranch,"globe-2":Globe2,"graduation-cap":GraduationCap,"hard-hat":HardHat,"hash":Hash,"headphones":Headphones,"heart-pulse":HeartPulse,"home":Home,"image":Image,"inbox":Inbox,"key":Key,"languages":Languages,"layers":Layers,"library":Library,"line-chart":LineChart,"list-checks":ListChecks,"lock":Lock,"mail":Mail,"map":Map,"map-pin":MapPin,"megaphone":Megaphone,"menu":Menu,"message-circle":MessageCircle,"message-square":MessageSquare,"message-square-text":MessageSquareText,"moon-star":MoonStar,"navigation":Navigation,"notebook":Notebook,"notebook-pen":NotebookPen,"package":Package,"pause":Pause,"pen-line":PenLine,"pen-tool":PenTool,"phone":Phone,"phone-call":PhoneCall,"phone-incoming":PhoneIncoming,"play":Play,"plug":Plug,"plug-zap":PlugZap,"plus":Plus,"quote":Quote,"radar":Radar,"receipt":Receipt,"rocket":Rocket,"route":Route,"scale":Scale,"scan-line":ScanLine,"school":School,"search":Search,"send":Send,"settings-2":Settings2,"share-2":Share2,"shield-check":ShieldCheck,"shopping-bag":ShoppingBag,"shopping-cart":ShoppingCart,"sliders-horizontal":SlidersHorizontal,"star":Star,"stethoscope":Stethoscope,"table-2":Table2,"trending-up":TrendingUp,"truck":Truck,"user-check":UserCheck,"user-round":UserRound,"user-search":UserSearch,"users":Users,"utensils":Utensils,"video":Video,"workflow":Workflow,"wrench":Wrench,"x":X};

type Props={name:string;size?:number;className?:string};
export function Icon({name,size=24,className}:Props){
 if(name==='instagram')return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" className={className}><rect x="2" y="2" width="20" height="20" rx="5"/><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"/><line x1="17.5" x2="17.51" y1="6.5" y2="6.5"/></svg>;
 if(name==='whatsapp')return <svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" className={className}><path d="M17.47 14.38c-.3-.15-1.76-.87-2.03-.97-.27-.1-.47-.15-.67.15-.2.3-.77.97-.94 1.17-.17.2-.35.22-.65.07-.3-.15-1.26-.46-2.4-1.48-.89-.79-1.49-1.77-1.66-2.07-.17-.3-.02-.46.13-.61.13-.13.3-.35.45-.52.15-.17.2-.3.3-.5.1-.2.05-.37-.02-.52-.08-.15-.67-1.62-.92-2.22-.24-.58-.49-.5-.67-.51h-.57c-.2 0-.52.07-.8.37-.27.3-1.04 1.02-1.04 2.48 0 1.46 1.07 2.88 1.21 3.08.15.2 2.1 3.2 5.08 4.49.71.31 1.26.49 1.69.63.71.22 1.36.19 1.87.12.57-.09 1.76-.72 2.01-1.41.25-.69.25-1.29.17-1.41-.07-.12-.27-.2-.57-.35zM12.05 21.5h-.01a9.4 9.4 0 0 1-4.8-1.32l-.34-.2-3.57.94.95-3.48-.22-.36A9.43 9.43 0 1 1 12.05 21.5zm8.02-17.46A11.27 11.27 0 0 0 12.05.72 11.35 11.35 0 0 0 2.22 17.73L.6 23.64l6.05-1.59a11.3 11.3 0 0 0 5.4 1.38h.01A11.35 11.35 0 0 0 20.07 4.04z"/></svg>;
 if(name==='linkedin')return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" className={className}><path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z"/><rect width="4" height="12" x="2" y="9"/><circle cx="4" cy="4" r="2"/></svg>;
 const C=icons[name]||Layers;
 return <C size={size} aria-hidden="true" focusable="false" className={className} style={{display:'block',flexShrink:0}}/>;
}
