'use client';
import {useState} from 'react';
import {FileText,MessageSquare,Check,Plus,ShieldCheck,BarChart3,Layers} from 'lucide-react';
import {Lang,t,Copy,departments,industries} from '@/lib/content';
import {profiles,Profile} from '@/lib/page-profiles';
export function ProcessMock({profile,lang}:{profile:Profile;lang:Lang}){
 const c=(ru:string,en:string,ka:string)=>t([ru,en,ka],lang);const [stage,setStage]=useState(profile.kind==='chat'?0:1);
 return <div className={'process-mock mock-'+profile.kind}><div className="mock-chrome"><span>PRAXIS / WORKSPACE</span><span>{c('Демо','Demo','დემო')}</span></div><div className="mock-tabs">{[c('Входящий запрос','Incoming request','შემოსული მოთხოვნა'),c('Результат обработки','Processed result','დამუშავების შედეგი')].map((v,i)=><button key={i} onClick={()=>setStage(i)} aria-pressed={stage===i} className={stage===i?'active':''}>{v}</button>)}</div><div className="mock-body" key={stage}>{stage===0?<><div className="mock-source"><MessageSquare size={20}/><span>{c('Пример рабочего запроса','Example work request','სამუშაო მოთხოვნის მაგალითი')}</span></div><blockquote>{t(profile.input,lang)}</blockquote><div className="mock-path"><span><FileText size={16}/>{c('Данные','Data','მონაცემები')}</span><i/><span><Layers size={16}/>AI</span><i/><span><ShieldCheck size={16}/>{c('Проверка','Review','შემოწმება')}</span></div><button className="text-link" onClick={()=>setStage(1)}>{c('Показать результат','Show the result','შედეგის ნახვა')}<Plus size={16}/></button></>:<><div className="mock-source"><FileText size={20}/><span>{c('Подготовлено для проверки','Prepared for review','მომზადებულია შესამოწმებლად')}</span></div><table><thead><tr><th>{c('Поле','Field','ველი')}</th><th>{c('Значение','Value','მნიშვნელობა')}</th></tr></thead><tbody>{profile.rows.map(([k,v],i)=><tr key={i}><th scope="row">{t(k,lang)}</th><td>{t(v,lang)}</td></tr>)}</tbody></table><div className="mock-review"><Check size={15}/>{c('Следующий шаг — проверка сотрудником','Next: staff review','შემდეგ: თანამშრომლის შემოწმება')}</div></>}</div><p className="mock-disclaimer">{c('Иллюстрация сценария. Данные условные.','Illustrative workflow. Sample data.','სცენარის ილუსტრაცია. მონაცემები პირობითია.')}</p></div>
}
export function DeepSections({slug,lang,onChoose}:{slug:string;lang:Lang;onChoose:(s:string)=>void}){
 const profile=profiles[slug],d=departments.find(x=>x.slug===slug),industry=industries.find(x=>x.slug===slug);const [related,setRelated]=useState(0);
 const c=(ru:string,en:string,ka:string)=>t([ru,en,ka],lang);const relevant=d?industries.filter(i=>i.departments.includes(slug)):[];
 return <><section className="section deep-scenarios" id="scenarios"><div className="section-heading"><div><span className="eyebrow">01 / {c('РАБОЧИЕ СЦЕНАРИИ','WORKFLOWS','სამუშაო სცენარები')}</span><h2>{c('Где ИИ снимает рутину.','Where AI takes on routine work.','სად ამცირებს AI რუტინას.')}</h2></div><p>{c('Выберите один процесс для старта. Его можно проверить на ваших документах, диалогах и правилах.','Start with one workflow, tested against your documents, conversations and rules.','დაიწყეთ ერთი პროცესით და შეამოწმეთ თქვენს დოკუმენტებზე, დიალოგებსა და წესებზე.')}</p></div><div className="deep-cards">{profile.scenarios.map((s,i)=><article key={i}><span className="card-index">0{i+1}</span><h3>{t(s.title,lang)}</h3><p>{t(s.body,lang)}</p><button className="text-link" onClick={()=>onChoose(t(s.title,lang))}>{c('Разобрать этот сценарий','Explore this workflow','განვიხილოთ სცენარი')}<Plus size={16}/></button></article>)}</div></section>
 <section className="section deep-assurance"><div><span className="eyebrow">02 / {c('ПИЛОТ И КОНТРОЛЬ','PILOT & CONTROL','პილოტი და კონტროლი')}</span><h2>{c('Проверяем на вашей работе.','Tested on your actual work.','ვამოწმებთ თქვენს სამუშაოზე.')}</h2><p>{t(profile.control,lang)}</p></div><div className="assurance-facts"><article><Layers size={21}/><div><h3>{c('Источники и интеграции','Sources and integrations','წყაროები და ინტეგრაციები')}</h3><p>{profile.systems.split(' · ').map(v=>{const parts=v.split(' / ');return parts.length===1?v:lang==='ru'?parts[0]:lang==='en'?parts[1]:({'catalogue':'კატალოგი','Catalogue':'კატალოგი','knowledge base':'ცოდნის ბაზა','documents':'დოკუმენტები','Portal':'პორტალი','source documents':'პირველადი დოკუმენტები','Workflows':'პროცესები','reports':'ანგარიშები','inventory':'მარაგი','property feed':'ობიექტების ბაზა','unit inventory':'ბინების ბაზა','Procedures':'რეგლამენტები','Reservations':'ჯავშნები','menu':'მენიუ','tasks':'ამოცანები','Itineraries':'მარშრუტები','rates':'ტარიფები','Schedule':'განრიგი','chat':'მესენჯერი','programmes':'პროგრამები'} as Record<string,string>)[parts[1]]||parts[1]}).join(' · ')}</p><small>{c('Проверим доступы и совместимость до оценки проекта.','We check access and compatibility before estimating the project.','პროექტის შეფასებამდე ვამოწმებთ წვდომასა და თავსებადობას.')}</small></div></article><article><BarChart3 size={21}/><div><h3>{c('Что измеряем','What we measure','რას ვზომავთ')}</h3><p>{t((d?.metric||industry?.metric) as Copy,lang)}</p><small>{c('Сравниваем с исходным процессом, включая время проверки человеком.','Compare with your baseline, including human review time.','ვადარებთ საწყის პროცესს, ადამიანის შემოწმების დროის ჩათვლით.')}</small></div></article></div></section>
 {d&&relevant.length>0&&<section className="section related-scenarios"><div className="section-heading"><div><span className="eyebrow">{c('В КОНТЕКСТЕ БИЗНЕСА','IN YOUR BUSINESS','ბიზნესის კონტექსტში')}</span><h2>{c('Одна роль. Разные процессы.','One role. Different workflows.','ერთი როლი. სხვადასხვა პროცესი.')}</h2></div></div><div className="related-tabs" aria-label={c('Выберите отрасль','Choose industry','აირჩიეთ ინდუსტრია')}>{relevant.map((r,i)=><button key={r.slug} aria-pressed={related===i} onClick={()=>setRelated(i)}>{t(r.name,lang)}</button>)}</div><div className="related-detail"><div><h3>{t(relevant[related].promise,lang)}</h3><p>{t(relevant[related].solution,lang)}</p></div><a className="button secondary" href={'/'+lang+'/industries/'+relevant[related].slug}>{c('Сценарии для отрасли','Industry workflows','ინდუსტრიის სცენარები')}</a></div></section>}
 <section className="section faq"><div><span className="eyebrow">FAQ</span><h2>{c('Вопросы по делу.','Practical questions.','პრაქტიკული კითხვები.')}</h2></div><div>{profile.faq.map(([q,a],i)=><details key={i}><summary>{t(q,lang)}<Plus size={18}/></summary><p>{t(a,lang)}</p></details>)}</div></section></>
}
export function SolutionExamples({lang}:{lang:Lang}){const c=(ru:string,en:string,ka:string)=>t([ru,en,ka],lang);return <section className="section"><div className="section-heading"><div><span className="eyebrow">{c('ЧТО МОЖНО ВНЕДРИТЬ','WHAT WE CAN BUILD','რისი დანერგვა შეიძლება')}</span><h2>{c('Решения, у которых есть задача.','Solutions with a clear purpose.','გადაწყვეტილებები მკაფიო ამოცანით.')}</h2></div></div><div className="deep-cards">{['sales','support','operations'].map(slug=><article key={slug}><span className="eyebrow">{t(departments.find(d=>d.slug===slug)!.name,lang)}</span><h3>{t(profiles[slug].scenarios[0].title,lang)}</h3><p>{t(profiles[slug].scenarios[0].body,lang)}</p><a className="text-link" href={'/'+lang+'/departments/'+slug}>{c('Посмотреть сценарии','Explore workflows','სცენარების ნახვა')}<Plus size={16}/></a></article>)}</div></section>}
