import type {Copy} from './content';

// Self-contained answer under the hero of each department and industry page [ru, en, ka]:
// what AI does there in Georgia, integrations (examples, checked per project), control,
// timeline, price and the pilot metric. Written to be quoted by AI search as a whole passage.
// Prices follow lib/pricing.ts: training, implementation, development and monthly support.
export const detailAnswers:Record<string,{q:Copy;a:Copy}>={
 sales:{
  q:['Что ИИ делает в отделе продаж и сколько это стоит?','What does AI do for a sales team, and what does it cost?','რას აკეთებს AI გაყიდვების განყოფილებაში და რა ღირს?'],
  a:['ИИ-ассистент отвечает на заявки в WhatsApp, Telegram и на сайте за секунды, на грузинском, английском или русском. Он уточняет задачу, объём, бюджет и сроки, создаёт сделку в CRM (например, amoCRM, Bitrix24 или HubSpot) и передаёт менеджеру тёплого клиента с резюме переписки. Ночью и в выходные заявки не теряются, а утром менеджер видит готовый список. Скидки и условия ассистент берёт только из ваших правил, сделку ведёт человек. Внедрение одного сценария с интеграцией в вашу систему стоит от 3 200 ₾, платформа и сопровождение по желанию — от 550 ₾ в месяц. Пилот на реальных заявках занимает 2–4 недели. Результат измеряем по времени первого ответа, полноте карточек в CRM и доле заявок, дошедших до встречи.',
   'An AI assistant replies to enquiries on WhatsApp, Telegram and your website within seconds, in Georgian, English or Russian. It clarifies the need, quantity, budget and timing, creates a deal in your CRM (for example amoCRM, Bitrix24 or HubSpot) and hands a warm lead to a manager with a summary of the chat. Leads that arrive at night or at weekends are no longer lost, and the team starts the morning with a ready list. Discounts and terms come only from your rules, and a person runs the deal. Implementing one workflow integrated with your system starts at 3,200 ₾, with optional platform and support from 550 ₾ a month. A pilot on real enquiries takes 2–4 weeks. We measure first response time, CRM completeness and the share of enquiries that reach a meeting.',
   'AI ასისტენტი WhatsApp‑ში, Telegram‑სა და საიტზე წამებში პასუხობს მოთხოვნებს ქართულად, ინგლისურად ან რუსულად. ის აზუსტებს საჭიროებას, მოცულობას, ბიუჯეტსა და ვადებს, ქმნის გარიგებას CRM‑ში (მაგალითად, amoCRM‑ში, Bitrix24‑ში ან HubSpot‑ში) და თბილ კლიენტს მენეჯერს მიმოწერის შეჯამებით გადასცემს. ღამით და შაბათ‑კვირას მოთხოვნები აღარ იკარგება, დილით კი მენეჯერი მზა სიას ხედავს. ფასდაკლებებსა და პირობებს ასისტენტი მხოლოდ თქვენი წესებიდან იღებს, გარიგებას ადამიანი წარმართავს. ერთი სცენარის დანერგვა თქვენს სისტემასთან ინტეგრაციით ღირს 3 200 ₾‑დან, პლატფორმა და მხარდაჭერა სურვილისამებრ — 550 ₾‑დან თვეში. პილოტი რეალურ მოთხოვნებზე 2–4 კვირა გრძელდება. შედეგს ვზომავთ პირველი პასუხის დროით, CRM‑ის სისრულითა და შეხვედრამდე მისული მოთხოვნების წილით.']
 },
 marketing:{
  q:['Что ИИ делает в маркетинге и сколько это стоит?','What does AI do for marketing, and what does it cost?','რას აკეთებს AI მარკეტინგში და რა ღირს?'],
  a:['ИИ готовит черновики постов, рассылок, описаний и рекламных текстов по вашему брендбуку и сразу адаптирует их под каналы и три языка: грузинский, английский и русский. Каждое утро он собирает сводку по кампаниям из рекламных кабинетов и аналитики (например, Meta и Google Analytics), а один материал превращает в версии для сайта, соцсетей и email. Правила бренда, запретные слова и обращение к клиенту фиксируем заранее. Публикует всегда человек. Чаще всего начинают с обучения команды (от 1 900 ₾) или с внедрения готовых инструментов под ваш процесс (от 3 200 ₾), сопровождение — от 550 ₾ в месяц. Пилот на одной задаче занимает 2–4 недели. Результат измеряем по времени выпуска материала, числу правок и соблюдению требований бренда.',
   'AI drafts posts, newsletters, product descriptions and ad copy from your brand book and adapts them to each channel and to Georgian, English and Russian. Every morning it compiles a campaign summary from your ad accounts and analytics (for example Meta and Google Analytics), and turns one piece of content into versions for the website, social media and email. Brand rules, banned words and the way you address customers are agreed upfront, and a person always publishes. Most teams start with training (from 1,900 ₾) or with implementing ready tools for their process (from 3,200 ₾); support starts at 550 ₾ a month. A pilot on one task takes 2–4 weeks. We measure production time, the number of revisions and brand compliance.',
   'AI ამზადებს პოსტების, გზავნილების, აღწერებისა და სარეკლამო ტექსტების მონახაზებს თქვენი ბრენდბუქით და მაშინვე არგებს მათ არხებსა და სამ ენას: ქართულს, ინგლისურსა და რუსულს. ყოველ დილით ის აგროვებს კამპანიების შეჯამებას სარეკლამო კაბინეტებიდან და ანალიტიკიდან (მაგალითად, Meta‑დან და Google Analytics‑იდან), ერთ მასალას კი საიტის, სოციალური ქსელებისა და ელფოსტის ვერსიებად აქცევს. ბრენდის წესებს, აკრძალულ სიტყვებსა და კლიენტისადმი მიმართვას წინასწარ ვაფიქსირებთ. აქვეყნებს ყოველთვის ადამიანი. ყველაზე ხშირად იწყებენ გუნდის სწავლებით (1 900 ₾‑დან) ან მზა ინსტრუმენტების დანერგვით თქვენს პროცესზე (3 200 ₾‑დან), მხარდაჭერა — 550 ₾‑დან თვეში. პილოტი ერთ ამოცანაზე 2–4 კვირა გრძელდება. შედეგს ვზომავთ მასალის მომზადების დროით, შესწორებების რაოდენობითა და ბრენდის მოთხოვნების დაცვით.']
 },
 support:{
  q:['Что ИИ делает в поддержке клиентов и сколько это стоит?','What does AI do for customer support, and what does it cost?','რას აკეთებს AI მომხმარებელთა მხარდაჭერაში და რა ღირს?'],
  a:['Чат-бот отвечает клиентам в WhatsApp, Telegram и на сайте круглосуточно, на грузинском, английском и русском, и берёт ответы только из вашей базы знаний: цены, доставка, статусы, правила возврата. Если ответа в базе нет или клиент недоволен, диалог сразу переходит к оператору вместе с историей, и клиенту не нужно повторять вопрос. Операторам ассистент предлагает черновики ответов и сам распределяет обращения по темам в helpdesk (например, Zendesk, Intercom или Jivo). Голосовые сообщения он расшифровывает и отвечает текстом. Внедрение одного сценария с интеграцией в вашу систему стоит от 3 200 ₾, платформа и сопровождение по желанию — от 550 ₾ в месяц. Пилот на реальных обращениях — 2–4 недели. Результат измеряем по времени ответа, точности и доле передач оператору.',
   'The chatbot answers customers on WhatsApp, Telegram and your website around the clock, in Georgian, English and Russian, using only your knowledge base: prices, delivery, order status and return rules. When the answer is not in the base or a customer is unhappy, the chat moves to an agent with the full history, so the customer does not repeat the question. For agents, the assistant drafts replies and routes tickets by topic in your helpdesk (for example Zendesk, Intercom or Jivo). It transcribes voice messages and replies in text. Implementing one workflow integrated with your system starts at 3,200 ₾, with optional platform and support from 550 ₾ a month. A pilot on real conversations takes 2–4 weeks. We measure response time, accuracy and the share of chats handed to an agent.',
   'ჩატბოტი კლიენტებს WhatsApp‑ში, Telegram‑სა და საიტზე დღე‑ღამის განმავლობაში პასუხობს ქართულად, ინგლისურად და რუსულად და პასუხებს მხოლოდ თქვენი ცოდნის ბაზიდან იღებს: ფასები, მიწოდება, სტატუსები, დაბრუნების წესები. თუ პასუხი ბაზაში არ არის ან კლიენტი უკმაყოფილოა, საუბარი მაშინვე ოპერატორს ისტორიასთან ერთად გადაეცემა და კლიენტს კითხვის გამეორება არ უწევს. ოპერატორებს ასისტენტი პასუხების მონახაზებს სთავაზობს და მიმართვებს თემების მიხედვით ანაწილებს helpdesk‑ში (მაგალითად, Zendesk‑ში, Intercom‑ში ან Jivo‑ში). ხმოვან შეტყობინებებს შიფრავს და ტექსტით პასუხობს. ერთი სცენარის დანერგვა თქვენს სისტემასთან ინტეგრაციით ღირს 3 200 ₾‑დან, პლატფორმა და მხარდაჭერა სურვილისამებრ — 550 ₾‑დან თვეში. პილოტი რეალურ მიმართვებზე 2–4 კვირა გრძელდება. შედეგს ვზომავთ პასუხის დროით, სიზუსტითა და ოპერატორზე გადაცემის წილით.']
 },
 operations:{
  q:['Что ИИ делает в бэк-офисе и сколько это стоит?','What does AI do for back-office operations, and what does it cost?','რას აკეთებს AI ბექ‑ოფისში და რა ღირს?'],
  a:['ИИ извлекает данные из PDF, сканов, писем и форм, раскладывает их по полям и передаёт в вашу систему: 1С, ERP, CRM или Google Workspace. Входящие письма и заявки он распределяет по ответственным, а внутренний ассистент отвечает сотрудникам по регламентам и находит нужный документ. Если ИИ не уверен в значении, поле подсвечивается и уходит человеку на подтверждение. Требования к коммерческой тайне и персональным данным фиксируем до старта, данные не используются для обучения публичных моделей. Внедрение готовых инструментов под ваш процесс — от 3 200 ₾, разработка с интеграцией в 1С или ERP — от 6 700 ₾, сопровождение — от 550 ₾ в месяц. Пилот на одном потоке документов занимает 2–4 недели. Результат измеряем по времени обработки, числу возвратов на исправление и ручных действий.',
   'AI extracts data from PDFs, scans, emails and forms, maps it to fields and sends it to your system: 1C, an ERP, a CRM or Google Workspace. It routes incoming emails and requests to the right owners, and an internal assistant answers staff questions from your policies and finds the right document. When AI is unsure about a value, the field is highlighted and goes to a person for confirmation. Trade-secret and personal-data rules are agreed before we start, and your data is not used to train public models. Implementing ready tools for your process starts at 3,200 ₾, custom development with 1C or ERP integration at 6,700 ₾, and support at 550 ₾ a month. A pilot on one document flow takes 2–4 weeks. We measure processing time, rework and manual steps.',
   'AI იღებს მონაცემებს PDF‑ებიდან, სკანებიდან, წერილებიდან და ფორმებიდან, ანაწილებს ველებად და გადასცემს თქვენს სისტემას: 1C‑ს, ERP‑ს, CRM‑ს ან Google Workspace‑ს. შემოსულ წერილებსა და მოთხოვნებს პასუხისმგებლებზე ანაწილებს, შიდა ასისტენტი კი თანამშრომლებს წესების მიხედვით პასუხობს და საჭირო დოკუმენტს პოულობს. თუ AI მნიშვნელობაში დარწმუნებული არ არის, ველი მოინიშნება და ადამიანს დასადასტურებლად გადაეცემა. კომერციული საიდუმლოებისა და პერსონალური მონაცემების მოთხოვნებს დაწყებამდე ვაფიქსირებთ, მონაცემები საჯარო მოდელების სწავლებისთვის არ გამოიყენება. მზა ინსტრუმენტების დანერგვა თქვენს პროცესზე — 3 200 ₾‑დან, შემუშავება 1C‑სთან ან ERP‑სთან ინტეგრაციით — 6 700 ₾‑დან, მხარდაჭერა — 550 ₾‑დან თვეში. პილოტი დოკუმენტების ერთ ნაკადზე 2–4 კვირა გრძელდება. შედეგს ვზომავთ დამუშავების დროით, შესასწორებლად დაბრუნებებითა და ხელით შესრულებული ქმედებებით.']
 },
 hr:{
  q:['Что ИИ делает в HR и сколько это стоит?','What does AI do for HR, and what does it cost?','რას აკეთებს AI HR‑ში და რა ღირს?'],
  a:['Корпоративный ИИ-ассистент отвечает сотрудникам на вопросы по внутренним правилам: отпуска, командировки, документы, доступы. Он работает в привычном мессенджере, например Slack, Microsoft Teams или Telegram, и ссылается на конкретный регламент. Для новичков он собирает трек адаптации под роль и готовит учебные материалы и тесты из ваших инструкций. Доступ настраивается по ролям: стажёр не увидит данные о зарплатах. Внутренние документы используются только в вашем решении. Внедрение готового ассистента на вашей базе знаний — от 3 200 ₾, разработка с интеграцией в HR-систему — от 6 700 ₾, сопровождение — от 550 ₾ в месяц. Пилот на одном отделе занимает 2–4 недели. Результат измеряем по времени поиска ответа, освоению сценариев и обратной связи сотрудников.',
   'A company AI assistant answers employees’ questions about internal rules: leave, business trips, documents and access. It works in the messenger your team already uses, such as Slack, Microsoft Teams or Telegram, and cites the exact policy. For new hires it builds a role-based onboarding track and prepares training materials and quizzes from your instructions. Access is role-based, so an intern cannot see salary data, and internal documents are used only inside your solution. Implementing a ready assistant on your knowledge base starts at 3,200 ₾, custom development with HR system integration at 6,700 ₾, and support at 550 ₾ a month. A pilot in one department takes 2–4 weeks. We measure time to find answers, scenario adoption and employee feedback.',
   'კორპორატიული AI ასისტენტი თანამშრომლებს შიდა წესებზე პასუხობს: შვებულება, მივლინება, დოკუმენტები, წვდომები. ის მუშაობს ნაცნობ მესენჯერში, მაგალითად Slack‑ში, Microsoft Teams‑ში ან Telegram‑ში, და კონკრეტულ წესზე მიუთითებს. ახალი თანამშრომლებისთვის როლის მიხედვით ადაპტაციის გეგმას ადგენს და თქვენი ინსტრუქციებიდან სასწავლო მასალებსა და ტესტებს ამზადებს. წვდომა როლების მიხედვით იმართება: სტაჟიორი ხელფასების მონაცემებს ვერ ნახავს. შიდა დოკუმენტები მხოლოდ თქვენს გადაწყვეტაში გამოიყენება. მზა ასისტენტის დანერგვა თქვენს ცოდნის ბაზაზე — 3 200 ₾‑დან, შემუშავება HR სისტემასთან ინტეგრაციით — 6 700 ₾‑დან, მხარდაჭერა — 550 ₾‑დან თვეში. პილოტი ერთ განყოფილებაზე 2–4 კვირა გრძელდება. შედეგს ვზომავთ პასუხის ძიების დროით, სცენარების ათვისებითა და თანამშრომლების უკუკავშირით.']
 },
 finance:{
  q:['Что ИИ делает в бухгалтерии и сколько это стоит?','What does AI do for accounting, and what does it cost?','რას აკეთებს AI ბუღალტერიაში და რა ღირს?'],
  a:['ИИ извлекает реквизиты, суммы и НДС из счетов, актов, накладных и чеков, даже из плохих сканов, и готовит черновики документов в учётной системе, например в 1С или SAP. Он сверяет взаиморасчёты с контрагентами по выпискам и подсвечивает расхождения, а чеки сотрудников превращает в черновик авансового отчёта. Документы ИИ не проводит: проводит бухгалтер, а нечёткие значения требуют его подтверждения. Данные остаются в вашем контуре и не используются для обучения публичных моделей. Внедрение готовых инструментов под ваш документооборот — от 3 200 ₾, разработка с интеграцией в 1С или ERP — от 6 700 ₾, сопровождение — от 550 ₾ в месяц. Пилот на одном типе документов занимает 2–4 недели. Результат измеряем по времени обработки, числу ошибок и объёму ручной сверки.',
   'AI extracts company details, amounts and VAT from invoices, acts, delivery notes and receipts, even poor scans, and prepares draft documents in your accounting system, for example 1C or SAP. It reconciles balances with counterparties from bank statements and highlights mismatches, and turns staff receipts into a draft expense report. AI does not post documents: an accountant does, and unclear values need their confirmation. Data stays within your environment and is not used to train public models. Implementing ready tools for your document flow starts at 3,200 ₾, custom development with 1C or ERP integration at 6,700 ₾, and support at 550 ₾ a month. A pilot on one document type takes 2–4 weeks. We measure processing time, errors and the amount of manual reconciliation.',
   'AI იღებს რეკვიზიტებს, თანხებსა და დღგ‑ს ინვოისებიდან, აქტებიდან, ზედნადებებიდან და ჩეკებიდან, ცუდი სკანებიდანაც კი, და ამზადებს დოკუმენტების მონახაზებს სააღრიცხვო სისტემაში, მაგალითად 1C‑ში ან SAP‑ში. ის ამონაწერებით ადარებს ანგარიშსწორებას კონტრაგენტებთან და მონიშნავს შეუსაბამობებს, თანამშრომლების ჩეკებს კი საავანსო ანგარიშის მონახაზად აქცევს. დოკუმენტებს AI არ ატარებს: ატარებს ბუღალტერი, ბუნდოვანი მნიშვნელობები კი მის დადასტურებას საჭიროებს. მონაცემები თქვენს გარემოში რჩება და საჯარო მოდელების სწავლებისთვის არ გამოიყენება. მზა ინსტრუმენტების დანერგვა თქვენს დოკუმენტბრუნვაზე — 3 200 ₾‑დან, შემუშავება 1C‑სთან ან ERP‑სთან ინტეგრაციით — 6 700 ₾‑დან, მხარდაჭერა — 550 ₾‑დან თვეში. პილოტი დოკუმენტის ერთ ტიპზე 2–4 კვირა გრძელდება. შედეგს ვზომავთ დამუშავების დროით, შეცდომების რაოდენობითა და ხელით შედარების მოცულობით.']
 },
 procurement:{
  q:['Что ИИ делает в закупках и сколько это стоит?','What does AI do for procurement, and what does it cost?','რას აკეთებს AI შესყიდვებში და რა ღირს?'],
  a:['ИИ извлекает цены, сроки поставки и условия оплаты из коммерческих предложений в PDF, Excel и письмах, приводит их к единым единицам и собирает сравнительную таблицу с рейтингом поставщиков. Он сверяет спецификации, счета и договоры, подсвечивает расхождения в цене, количестве и условиях и готовит вопросы поставщику, если чего-то не хватает. Статусы поставок обновляются из писем перевозчиков. Заказы ИИ не размещает: решение принимает менеджер, а правила тендерной политики задаются заранее. Внедрение готовых инструментов — от 3 200 ₾, разработка с интеграцией в ERP (например, SAP, Microsoft Dynamics или 1С) — от 6 700 ₾, сопровождение — от 550 ₾ в месяц. Пилот на одной категории закупок занимает 2–4 недели. Результат измеряем по времени сравнения, полноте условий и числу исправлений.',
   'AI extracts prices, lead times and payment terms from supplier quotes in PDFs, spreadsheets and emails, normalises units and builds a comparison table with a supplier ranking. It checks specifications, invoices and contracts, flags price, quantity and term mismatches, and drafts questions to suppliers when something is missing. Delivery statuses update from carrier emails. AI does not place orders: a manager decides, and your tender policy rules are set upfront. Implementing ready tools starts at 3,200 ₾, custom development with ERP integration (for example SAP, Microsoft Dynamics or 1C) at 6,700 ₾, and support at 550 ₾ a month. A pilot on one purchasing category takes 2–4 weeks. We measure comparison time, completeness of terms and the number of corrections.',
   'AI იღებს ფასებს, მიწოდების ვადებსა და გადახდის პირობებს კომერციული შეთავაზებებიდან PDF‑ში, Excel‑სა და წერილებში, ერთიან ერთეულებზე გადაჰყავს და მომწოდებლების რეიტინგით შედარების ცხრილს ადგენს. ის ადარებს სპეციფიკაციებს, ინვოისებსა და ხელშეკრულებებს, მონიშნავს შეუსაბამობებს ფასში, რაოდენობასა და პირობებში და თუ რამე აკლია, მომწოდებლისთვის კითხვებს ამზადებს. მიწოდების სტატუსები გადამზიდავების წერილებიდან ახლდება. შეკვეთებს AI არ აფორმებს: გადაწყვეტილებას მენეჯერი იღებს, სატენდერო პოლიტიკის წესები კი წინასწარ განისაზღვრება. მზა ინსტრუმენტების დანერგვა — 3 200 ₾‑დან, შემუშავება ERP‑სთან ინტეგრაციით (მაგალითად, SAP, Microsoft Dynamics ან 1C) — 6 700 ₾‑დან, მხარდაჭერა — 550 ₾‑დან თვეში. პილოტი შესყიდვების ერთ კატეგორიაზე 2–4 კვირა გრძელდება. შედეგს ვზომავთ შედარების დროით, პირობების სისრულითა და შესწორებების რაოდენობით.']
 },
 leadership:{
  q:['С чего начать внедрение ИИ в компании и сколько это стоит?','Where should a company start with AI, and what does it cost?','საიდან დავიწყოთ AI‑ს დანერგვა კომპანიაში და რა ღირს?'],
  a:['Начинать стоит с одного процесса, где много повторяющейся работы и есть понятная метрика: заявки клиентов, ответы в мессенджерах или документы. На бесплатном аудите мы разбираем процессы, считаем эффект в часах и лари и выбираем пилот с самой понятной экономикой. Если проект не окупается, говорим об этом прямо. Пилот идёт 2–4 недели на ваших реальных данных с фиксированной ценой, после чего решение масштабируется на другие отделы без роста штата. Руководитель получает сводки по ключевым показателям в привычном канале, например в Telegram или Bitrix24. Обучение руководителей и команды стоит от 1 900 ₾, внедрение под процесс — от 3 200 ₾, разработка решения — от 6 700 ₾. Права на созданные решения и инструкции передаём вам. Результат измеряем по затратам на процесс, времени сотрудников и качеству результата.',
   'Start with one workflow that has a lot of repetitive work and a clear metric: customer enquiries, messenger replies or documents. In a free audit we review your processes, estimate the effect in hours and lari, and choose the pilot with the clearest economics. If a project will not pay back, we say so plainly. The pilot runs for 2–4 weeks on your real data at a fixed price, and the solution then scales to other departments without adding headcount. Leadership gets summaries of key metrics in a familiar channel, for example Telegram or Bitrix24. Training for managers and teams starts at 1,900 ₾, implementation for a specific process at 3,200 ₾, and custom development at 6,700 ₾. Rights to the solutions and documentation are handed over to you. We measure process cost, staff time and the quality of the result.',
   'დაწყება ღირს ერთი პროცესით, სადაც ბევრი განმეორებადი სამუშაოა და მკაფიო მეტრიკა: კლიენტების მოთხოვნები, მესენჯერებში პასუხები ან დოკუმენტები. უფასო აუდიტზე ვაანალიზებთ პროცესებს, ვითვლით ეფექტს საათებსა და ლარში და ვირჩევთ პილოტს ყველაზე გასაგები ეკონომიკით. თუ პროექტი არ ანაზღაურდება, ამას პირდაპირ ვამბობთ. პილოტი 2–4 კვირა გრძელდება თქვენს რეალურ მონაცემებზე ფიქსირებული ფასით, შემდეგ კი გადაწყვეტა სხვა განყოფილებებზე ვრცელდება შტატის ზრდის გარეშე. ხელმძღვანელი ძირითადი მაჩვენებლების შეჯამებებს ნაცნობ არხში იღებს, მაგალითად Telegram‑ში ან Bitrix24‑ში. ხელმძღვანელებისა და გუნდის სწავლება — 1 900 ₾‑დან, დანერგვა კონკრეტულ პროცესზე — 3 200 ₾‑დან, ინდივიდუალური შემუშავება — 6 700 ₾‑დან. შექმნილ გადაწყვეტებსა და ინსტრუქციებზე უფლებებს თქვენ გადმოგცემთ. შედეგს ვზომავთ პროცესის ხარჯით, თანამშრომლების დროითა და შედეგის ხარისხით.']
 },
 retail:{
  q:['Что ИИ делает для интернет-магазина и сколько это стоит?','What does AI do for an online store, and what does it cost?','რას აკეთებს AI ონლაინ მაღაზიისთვის და რა ღირს?'],
  a:['ИИ-консультант в Instagram, WhatsApp и на сайте подбирает товар по описанию покупателя, проверяет наличие и размеры в вашем каталоге и отвечает на грузинском, английском или русском. Он предлагает сопутствующие позиции, напоминает о брошенной корзине и отвечает на вопрос «где мой заказ» по данным вашей системы, например Shopify, WooCommerce, 1С-Битрикс или RetailCRM. Возвраты и жалобы уходят менеджеру. Ассистент предлагает только товары, которые есть на складе, и не выходит за лимиты скидок. Внедрение одного сценария с интеграцией в вашу систему стоит от 3 200 ₾, платформа и сопровождение по желанию — от 550 ₾ в месяц. Пилот на реальных диалогах занимает 2–4 недели. Результат измеряем по времени ответа и доле ответов без исправлений.',
   'An AI shopping assistant on Instagram, WhatsApp and your website finds products from a shopper’s description, checks stock and sizes in your catalogue and replies in Georgian, English or Russian. It suggests related items, follows up on abandoned carts and answers “where is my order” from your system, for example Shopify, WooCommerce, 1C-Bitrix or RetailCRM. Returns and complaints go to a manager. The assistant offers only items that are in stock and stays within your discount limits. Implementing one workflow integrated with your system starts at 3,200 ₾, with optional platform and support from 550 ₾ a month. A pilot on real conversations takes 2–4 weeks. We measure response time and the share of replies that need no correction.',
   'AI კონსულტანტი Instagram‑ში, WhatsApp‑სა და საიტზე მყიდველის აღწერით პროდუქტს არჩევს, თქვენს კატალოგში მარაგსა და ზომებს ამოწმებს და ქართულად, ინგლისურად ან რუსულად პასუხობს. ის თანმხლებ პროდუქტებს სთავაზობს, მიტოვებულ კალათაზე შეახსენებს და კითხვას „სად არის ჩემი შეკვეთა“ თქვენი სისტემის მონაცემებით პასუხობს, მაგალითად Shopify‑დან, WooCommerce‑დან, 1C‑Bitrix‑იდან ან RetailCRM‑იდან. დაბრუნებები და საჩივრები მენეჯერს გადაეცემა. ასისტენტი მხოლოდ მარაგში არსებულ პროდუქტს სთავაზობს და ფასდაკლების ლიმიტებს არ სცდება. ერთი სცენარის დანერგვა თქვენს სისტემასთან ინტეგრაციით ღირს 3 200 ₾‑დან, პლატფორმა და მხარდაჭერა სურვილისამებრ — 550 ₾‑დან თვეში. პილოტი რეალურ დიალოგებზე 2–4 კვირა გრძელდება. შედეგს ვზომავთ პასუხის დროითა და შესწორების გარეშე პასუხების წილით.']
 },
 wholesale:{
  q:['Что ИИ делает в оптовой торговле и сколько это стоит?','What does AI do for wholesale and distribution, and what does it cost?','რას აკეთებს AI საბითუმო ვაჭრობაში და რა ღირს?'],
  a:['ИИ принимает заказы клиентов в любом формате: PDF, Excel, письмо или сообщение в WhatsApp. Он сопоставляет позиции с вашей номенклатурой, даже если клиент называет товар по-своему, и готовит черновик счёта в учётной системе, например в 1С, МойСклад или SAP. Прайсы поставщиков он приводит к единому виду и обновляет, а дилерам отвечает о наличии и ценах в мессенджере. Скидки ИИ даёт только в рамках профиля клиента в вашей системе. Счёт проверяет и отправляет менеджер. Внедрение готовых инструментов под ваш процесс — от 3 200 ₾, разработка с интеграцией в учётную систему — от 6 700 ₾, сопровождение — от 550 ₾ в месяц. Пилот на одном потоке заказов занимает 2–4 недели. Результат измеряем по времени подготовки счёта и числу исправленных позиций.',
   'AI takes customer orders in any format: a PDF, a spreadsheet, an email or a WhatsApp message. It matches line items to your item master, even when customers use their own names for products, and prepares a draft invoice in your accounting system, for example 1C, MoySklad or SAP. It normalises and updates supplier price lists and answers dealers’ stock and price questions in a messenger. Discounts follow only the customer’s profile in your system, and a manager reviews and sends the invoice. Implementing ready tools for your process starts at 3,200 ₾, custom development with accounting system integration at 6,700 ₾, and support at 550 ₾ a month. A pilot on one order flow takes 2–4 weeks. We measure invoice preparation time and the number of corrected line items.',
   'AI კლიენტების შეკვეთებს ნებისმიერ ფორმატში იღებს: PDF, Excel, წერილი ან შეტყობინება WhatsApp‑ში. ის პოზიციებს თქვენს ნომენკლატურას უთანადებს, მაშინაც კი, როცა კლიენტი პროდუქტს თავისებურად უწოდებს, და ინვოისის მონახაზს სააღრიცხვო სისტემაში ამზადებს, მაგალითად 1C‑ში, MoySklad‑ში ან SAP‑ში. მომწოდებლების ფასების სიებს ერთ ფორმაზე გადაჰყავს და ანახლებს, დილერებს კი მარაგსა და ფასებზე მესენჯერში პასუხობს. ფასდაკლებას AI მხოლოდ თქვენს სისტემაში კლიენტის პროფილის ფარგლებში აძლევს. ინვოისს მენეჯერი ამოწმებს და აგზავნის. მზა ინსტრუმენტების დანერგვა თქვენს პროცესზე — 3 200 ₾‑დან, შემუშავება სააღრიცხვო სისტემასთან ინტეგრაციით — 6 700 ₾‑დან, მხარდაჭერა — 550 ₾‑დან თვეში. პილოტი შეკვეთების ერთ ნაკადზე 2–4 კვირა გრძელდება. შედეგს ვზომავთ ინვოისის მომზადების დროითა და შესწორებული პოზიციების რაოდენობით.']
 },
 hotels:{
  q:['Что ИИ делает для отеля и сколько это стоит?','What does AI do for a hotel, and what does it cost?','რას აკეთებს AI სასტუმროსთვის და რა ღირს?'],
  a:['ИИ-консьерж отвечает гостям в WhatsApp, Instagram и на сайте круглосуточно и на языке гостя: грузинском, английском, русском и других. Он рассказывает о завтраках, трансферах, парковке и правилах заселения, проверяет свободные номера в вашей PMS (например, Opera, Cloudbeds, Bnovo или TravelLine) и принимает прямые бронирования без комиссии площадок. После выезда он просит оставить отзыв. Занятый номер ассистент не предложит, политику отмены соблюдает, а жалобы сразу передаёт администратору. Для отелей Аджарии и Тбилиси межсезонье — удобное время, чтобы настроить ассистента до сезона. Внедрение одного сценария с интеграцией в вашу систему стоит от 3 200 ₾, платформа и сопровождение по желанию — от 550 ₾ в месяц. Пилот — 2–4 недели. Результат измеряем по времени ответа и числу вопросов, где понадобился администратор.',
   'An AI concierge answers guests on WhatsApp, Instagram and your website around the clock and in the guest’s language: Georgian, English, Russian and others. It explains breakfast, transfers, parking and check-in rules, checks availability in your PMS (for example Opera, Cloudbeds, Bnovo or TravelLine) and takes direct bookings without platform commissions. After check-out it asks for a review. The assistant never offers an occupied room, follows your cancellation policy and passes complaints straight to reception. For hotels in Adjara and Tbilisi, the off-season is a good time to set it up before the next season. Implementing one workflow integrated with your system starts at 3,200 ₾, with optional platform and support from 550 ₾ a month. A pilot takes 2–4 weeks. We measure response time and how many questions needed reception.',
   'AI კონსიერჟი სტუმრებს WhatsApp‑ში, Instagram‑სა და საიტზე დღე‑ღამის განმავლობაში სტუმრის ენაზე პასუხობს: ქართულად, ინგლისურად, რუსულად და სხვა ენებზე. ის ყვება საუზმეზე, ტრანსფერზე, პარკინგსა და შესახლების წესებზე, თავისუფალ ნომრებს თქვენს PMS‑ში ამოწმებს (მაგალითად, Opera‑ში, Cloudbeds‑ში, Bnovo‑ში ან TravelLine‑ში) და პირდაპირ ჯავშნებს პლატფორმების საკომისიოს გარეშე იღებს. გაწერის შემდეგ შეფასების დატოვებას სთხოვს. დაკავებულ ნომერს ასისტენტი არ შესთავაზებს, გაუქმების პოლიტიკას იცავს, საჩივრებს კი მაშინვე ადმინისტრატორს გადასცემს. აჭარისა და თბილისის სასტუმროებისთვის არასეზონი მოსახერხებელი დროა ასისტენტის სეზონამდე მოსამზადებლად. ერთი სცენარის დანერგვა თქვენს სისტემასთან ინტეგრაციით ღირს 3 200 ₾‑დან, პლატფორმა და მხარდაჭერა სურვილისამებრ — 550 ₾‑დან თვეში. პილოტი 2–4 კვირა გრძელდება. შედეგს ვზომავთ პასუხის დროითა და იმ კითხვების რაოდენობით, სადაც ადმინისტრატორი დასჭირდა.']
 },
 tourism:{
  q:['Что ИИ делает для туроператора и сколько это стоит?','What does AI do for a tour operator, and what does it cost?','რას აკეთებს AI ტუროპერატორისთვის და რა ღირს?'],
  a:['ИИ-ассистент в WhatsApp, Telegram и на сайте собирает бриф туриста: даты, состав группы, бюджет и интересы. Затем он подбирает отели, гидов и транспорт из вашей базы и готовит черновик программы со сметой для менеджера, пока турист ещё на связи. Он отвечает на грузинском, английском, русском и других языках, а во время поездки работает как консьерж на маршруте: напоминает о трансферах и отвечает на вопросы. Цены ассистент берёт только из ваших прайсов и с вашей маржой, программу и оплату подтверждает менеджер. Внедрение одного сценария с интеграцией в вашу систему стоит от 3 200 ₾, платформа и сопровождение по желанию — от 550 ₾ в месяц. Пилот — 2–4 недели. Результат измеряем по времени от запроса до первого предложения.',
   'An AI assistant on WhatsApp, Telegram and your website collects a traveller’s brief: dates, group, budget and interests. It then picks hotels, guides and transport from your database and drafts an itinerary with an estimate for a manager while the traveller is still in the chat. It replies in Georgian, English, Russian and other languages, and during the trip it acts as an on-route concierge, reminding about transfers and answering questions. Prices come only from your rate sheets with your margin, and a manager confirms the programme and payment. Implementing one workflow integrated with your system starts at 3,200 ₾, with optional platform and support from 550 ₾ a month. A pilot takes 2–4 weeks. We measure the time from enquiry to first proposal.',
   'AI ასისტენტი WhatsApp‑ში, Telegram‑სა და საიტზე ტურისტის ბრიფს აგროვებს: თარიღები, ჯგუფის შემადგენლობა, ბიუჯეტი და ინტერესები. შემდეგ თქვენი ბაზიდან სასტუმროებს, გიდებსა და ტრანსპორტს არჩევს და მენეჯერისთვის პროგრამის მონახაზს ხარჯთაღრიცხვით ამზადებს, სანამ ტურისტი ჯერ კიდევ კავშირზეა. ის ქართულად, ინგლისურად, რუსულად და სხვა ენებზე პასუხობს, მოგზაურობისას კი მარშრუტზე კონსიერჟად მუშაობს: ტრანსფერებზე შეახსენებს და კითხვებს პასუხობს. ფასებს ასისტენტი მხოლოდ თქვენი ფასების სიებიდან და თქვენი მარჟით იღებს, პროგრამასა და გადახდას მენეჯერი ადასტურებს. ერთი სცენარის დანერგვა თქვენს სისტემასთან ინტეგრაციით ღირს 3 200 ₾‑დან, პლატფორმა და მხარდაჭერა სურვილისამებრ — 550 ₾‑დან თვეში. პილოტი 2–4 კვირა გრძელდება. შედეგს ვზომავთ დროით მოთხოვნიდან პირველ შეთავაზებამდე.']
 },
 'real-estate':{
  q:['Что ИИ делает для агентства недвижимости и сколько это стоит?','What does AI do for an estate agency, and what does it cost?','რას აკეთებს AI უძრავი ქონების სააგენტოსთვის და რა ღირს?'],
  a:['ИИ принимает заявки из WhatsApp, Telegram, Instagram и с сайта круглосуточно, уточняет бюджет, район, тип объекта и сроки и подбирает варианты из вашей актуальной базы. Он отправляет фото и описание, записывает клиента на показ и создаёт карточку в CRM, например в amoCRM или Bitrix24, с резюме переписки. Голосовые сообщения он расшифровывает, отвечает на грузинском, английском и русском. Снятый с продажи объект ассистент не предложит, а юридические и налоговые вопросы передаёт специалисту. Внедрение одного сценария с интеграцией в вашу систему стоит от 3 200 ₾, платформа и сопровождение по желанию — от 550 ₾ в месяц. Пилот на реальных заявках занимает 2–4 недели. Результат измеряем по времени квалификации и доле обращений, дошедших до показа.',
   'AI takes enquiries from WhatsApp, Telegram, Instagram and your website around the clock, clarifies budget, district, property type and timing, and picks options from your current listings. It sends photos and descriptions, books viewings and creates a record in your CRM, for example amoCRM or Bitrix24, with a summary of the chat. It transcribes voice messages and replies in Georgian, English and Russian. The assistant never offers a property that is off the market, and passes legal and tax questions to a specialist. Implementing one workflow integrated with your system starts at 3,200 ₾, with optional platform and support from 550 ₾ a month. A pilot on real enquiries takes 2–4 weeks. We measure qualification time and the share of enquiries that reach a viewing.',
   'AI მოთხოვნებს WhatsApp‑იდან, Telegram‑იდან, Instagram‑იდან და საიტიდან დღე‑ღამის განმავლობაში იღებს, აზუსტებს ბიუჯეტს, უბანს, ობიექტის ტიპსა და ვადებს და თქვენი აქტუალური ბაზიდან ვარიანტებს არჩევს. ის აგზავნის ფოტოებსა და აღწერას, კლიენტს ჩვენებაზე წერს და CRM‑ში, მაგალითად amoCRM‑ში ან Bitrix24‑ში, ბარათს მიმოწერის შეჯამებით ქმნის. ხმოვან შეტყობინებებს შიფრავს, პასუხობს ქართულად, ინგლისურად და რუსულად. გაყიდვიდან მოხსნილ ობიექტს ასისტენტი არ შესთავაზებს, იურიდიულ და საგადასახადო კითხვებს კი სპეციალისტს გადასცემს. ერთი სცენარის დანერგვა თქვენს სისტემასთან ინტეგრაციით ღირს 3 200 ₾‑დან, პლატფორმა და მხარდაჭერა სურვილისამებრ — 550 ₾‑დან თვეში. პილოტი რეალურ მოთხოვნებზე 2–4 კვირა გრძელდება. შედეგს ვზომავთ კვალიფიკაციის დროითა და ჩვენებამდე მისული მიმართვების წილით.']
 },
 developers:{
  q:['Что ИИ делает для застройщика и сколько это стоит?','What does AI do for a property developer, and what does it cost?','რას აკეთებს AI დეველოპერისთვის და რა ღირს?'],
  a:['ИИ отвечает на заявки с рекламы в WhatsApp, Instagram и на сайте сразу, в том числе ночью, на грузинском, английском и русском. Он уточняет бюджет, цель покупки, площадь и срок, отправляет актуальные планировки и цены из шахматки (например, Profitbase или MacroCRM) и передаёт менеджеру тёплого клиента, готового к показу, с карточкой в CRM. Покупателей из-за рубежа ассистент ведёт на их языке. Скидок он не даёт, условия рассрочки не придумывает и одобрение ипотеки не обещает, а нестандартные вопросы передаёт старшему менеджеру. Внедрение одного сценария с интеграцией в вашу систему стоит от 3 200 ₾, платформа и сопровождение по желанию — от 550 ₾ в месяц. Пилот на реальных лидах занимает 2–4 недели. Результат измеряем по времени ответа и доле квалифицированных обращений.',
   'AI replies to ad leads on WhatsApp, Instagram and your website immediately, including at night, in Georgian, English and Russian. It clarifies budget, purpose of purchase, size and timing, sends current floor plans and prices from your inventory system (for example Profitbase or MacroCRM) and hands a warm, viewing-ready buyer to a manager with a CRM record. It serves buyers from abroad in their own language. It never gives discounts, invents instalment terms or promises mortgage approval, and passes non-standard questions to a senior manager. Implementing one workflow integrated with your system starts at 3,200 ₾, with optional platform and support from 550 ₾ a month. A pilot on real leads takes 2–4 weeks. We measure response time and the share of qualified enquiries.',
   'AI რეკლამიდან შემოსულ მოთხოვნებს WhatsApp‑ში, Instagram‑სა და საიტზე მაშინვე პასუხობს, ღამითაც, ქართულად, ინგლისურად და რუსულად. ის აზუსტებს ბიუჯეტს, შეძენის მიზანს, ფართობსა და ვადას, აგზავნის აქტუალურ გეგმარებებსა და ფასებს შახმატკიდან (მაგალითად, Profitbase‑იდან ან MacroCRM‑იდან) და ჩვენებისთვის მზად მყოფ თბილ კლიენტს მენეჯერს CRM‑ის ბარათით გადასცემს. საზღვარგარეთელ მყიდველებს ასისტენტი მათ ენაზე ემსახურება. ფასდაკლებას არ აძლევს, განვადების პირობებს არ იგონებს და იპოთეკის დამტკიცებას არ ჰპირდება, არასტანდარტულ კითხვებს კი უფროს მენეჯერს გადასცემს. ერთი სცენარის დანერგვა თქვენს სისტემასთან ინტეგრაციით ღირს 3 200 ₾‑დან, პლატფორმა და მხარდაჭერა სურვილისამებრ — 550 ₾‑დან თვეში. პილოტი რეალურ ლიდებზე 2–4 კვირა გრძელდება. შედეგს ვზომავთ პასუხის დროითა და კვალიფიციური მიმართვების წილით.']
 },
 restaurants:{
  q:['Что ИИ делает для ресторана и сколько это стоит?','What does AI do for a restaurant, and what does it cost?','რას აკეთებს AI რესტორნისთვის და რა ღირს?'],
  a:['ИИ-хостес принимает заявки на столы в Instagram, WhatsApp и на сайте круглосуточно, проверяет посадку в вашей системе (например, iiko, r_keeper или Poster) и подтверждает бронь на грузинском, английском или русском. По банкетам он собирает полный бриф для менеджера: дату, число гостей, меню, бюджет и пожелания. Он отвечает о меню, доставке и самовывозе. Блюда из стоп-листа ассистент не предлагает, бронь подтверждает только по данным системы, а нестандартные запросы передаёт администратору. Внедрение одного сценария с интеграцией в вашу систему стоит от 3 200 ₾, платформа и сопровождение по желанию — от 550 ₾ в месяц. Пилот на реальных заявках занимает 2–4 недели. Результат измеряем по времени сбора брифа и полноте заявки.',
   'An AI host takes table requests on Instagram, WhatsApp and your website around the clock, checks seating in your system (for example iiko, r_keeper or Poster) and confirms the booking in Georgian, English or Russian. For events it collects a full brief for the manager: date, number of guests, menu, budget and wishes. It answers questions about the menu, delivery and takeaway. The assistant never offers dishes on the stop list, confirms bookings only from system data and passes non-standard requests to the manager on duty. Implementing one workflow integrated with your system starts at 3,200 ₾, with optional platform and support from 550 ₾ a month. A pilot on real requests takes 2–4 weeks. We measure brief collection time and enquiry completeness.',
   'AI ჰოსტესი მაგიდების მოთხოვნებს Instagram‑ში, WhatsApp‑სა და საიტზე დღე‑ღამის განმავლობაში იღებს, ადგილებს თქვენს სისტემაში ამოწმებს (მაგალითად, iiko‑ში, r_keeper‑ში ან Poster‑ში) და ჯავშანს ქართულად, ინგლისურად ან რუსულად ადასტურებს. ბანკეტებისთვის მენეჯერს სრულ ბრიფს უგროვებს: თარიღი, სტუმრების რაოდენობა, მენიუ, ბიუჯეტი და სურვილები. ის პასუხობს მენიუზე, მიწოდებასა და წაღებაზე. სტოპ‑ლისტის კერძებს ასისტენტი არ სთავაზობს, ჯავშანს მხოლოდ სისტემის მონაცემებით ადასტურებს, არასტანდარტულ მოთხოვნებს კი ადმინისტრატორს გადასცემს. ერთი სცენარის დანერგვა თქვენს სისტემასთან ინტეგრაციით ღირს 3 200 ₾‑დან, პლატფორმა და მხარდაჭერა სურვილისამებრ — 550 ₾‑დან თვეში. პილოტი რეალურ მოთხოვნებზე 2–4 კვირა გრძელდება. შედეგს ვზომავთ ბრიფის შეგროვების დროითა და მოთხოვნის სისრულით.']
 },
 clinics:{
  q:['Что ИИ делает для клиники и сколько это стоит?','What does AI do for a clinic, and what does it cost?','რას აკეთებს AI კლინიკისთვის და რა ღირს?'],
  a:['ИИ-администратор отвечает пациентам в WhatsApp, Telegram и на сайте круглосуточно на грузинском, английском и русском. Он рассказывает об услугах, ценах и подготовке к приёму, записывает в свободные слоты вашей медицинской системы (например, Medesk, YCLIENTS или 1С:Медицина) и напоминает о визите накануне. После приёма он присылает рекомендации врача и просит оставить отзыв. Диагнозов и медицинских советов ассистент не даёт: если пациент описывает симптомы, он переводит диалог на врача или предлагает срочную запись. Медицинские данные обрабатываются по согласованным правилам доступа. Внедрение одного сценария с интеграцией в вашу систему стоит от 3 200 ₾, платформа и сопровождение по желанию — от 550 ₾ в месяц. Пилот — 2–4 недели. Результат измеряем по нагрузке на администратора и времени ответа.',
   'An AI receptionist answers patients on WhatsApp, Telegram and your website around the clock in Georgian, English and Russian. It explains services, prices and how to prepare for a visit, books free slots in your medical system (for example Medesk, YCLIENTS or 1C:Medicine) and sends a reminder the day before. After the visit it sends the doctor’s recommendations and asks for a review. The assistant never diagnoses or gives medical advice: when a patient describes symptoms, it hands the chat to a doctor or offers an urgent appointment. Medical data is handled under agreed access rules. Implementing one workflow integrated with your system starts at 3,200 ₾, with optional platform and support from 550 ₾ a month. A pilot takes 2–4 weeks. We measure reception workload and response time.',
   'AI ადმინისტრატორი პაციენტებს WhatsApp‑ში, Telegram‑სა და საიტზე დღე‑ღამის განმავლობაში ქართულად, ინგლისურად და რუსულად პასუხობს. ის ყვება მომსახურებაზე, ფასებსა და ვიზიტისთვის მომზადებაზე, თქვენი სამედიცინო სისტემის თავისუფალ სლოტებში წერს (მაგალითად, Medesk‑ში, YCLIENTS‑ში ან 1C:Medicine‑ში) და ვიზიტს წინა დღეს შეახსენებს. მიღების შემდეგ ექიმის რეკომენდაციებს უგზავნის და შეფასების დატოვებას სთხოვს. დიაგნოზებსა და სამედიცინო რჩევებს ასისტენტი არ იძლევა: თუ პაციენტი სიმპტომებს აღწერს, საუბარს ექიმს გადასცემს ან სასწრაფო ჩაწერას სთავაზობს. სამედიცინო მონაცემები შეთანხმებული წვდომის წესებით მუშავდება. ერთი სცენარის დანერგვა თქვენს სისტემასთან ინტეგრაციით ღირს 3 200 ₾‑დან, პლატფორმა და მხარდაჭერა სურვილისამებრ — 550 ₾‑დან თვეში. პილოტი 2–4 კვირა გრძელდება. შედეგს ვზომავთ ადმინისტრატორის დატვირთვითა და პასუხის დროით.']
 },
 logistics:{
  q:['Что ИИ делает в логистике и сколько это стоит?','What does AI do for logistics, and what does it cost?','რას აკეთებს AI ლოჯისტიკაში და რა ღირს?'],
  a:['ИИ извлекает данные из CMR, инвойсов, пакинг-листов и фото документов от водителей и заносит их в вашу TMS или учётную систему, например в 1С или SAP. Он сверяет документы между собой и подсвечивает расхождения, например вес в инвойсе и в пакинг-листе. Клиентам он отвечает на вопрос «где мой груз» в WhatsApp и Telegram по данным вашей системы, а водителям помогает с документами и маршрутом. Декларации ИИ не отправляет: спорные данные подтверждает сотрудник. Внедрение готовых инструментов под ваш документооборот — от 3 200 ₾, разработка с интеграцией в TMS, 1С или ERP — от 6 700 ₾, сопровождение — от 550 ₾ в месяц. Пилот на одном потоке документов занимает 2–4 недели. Результат измеряем по времени обработки и количеству ручных переносов данных.',
   'AI extracts data from CMRs, invoices, packing lists and drivers’ photos of documents and enters it into your TMS or accounting system, for example 1C or SAP. It cross-checks documents and flags mismatches, such as weight on the invoice versus the packing list. It answers customers’ “where is my cargo” questions on WhatsApp and Telegram from your system, and helps drivers with paperwork and routes. AI does not submit declarations: a staff member confirms disputed data. Implementing ready tools for your document flow starts at 3,200 ₾, custom development with TMS, 1C or ERP integration at 6,700 ₾, and support at 550 ₾ a month. A pilot on one document flow takes 2–4 weeks. We measure processing time and the number of manual data transfers.',
   'AI მონაცემებს CMR‑ებიდან, ინვოისებიდან, შეფუთვის სიებიდან და მძღოლების მიერ გადაღებული დოკუმენტების ფოტოებიდან იღებს და თქვენს TMS‑ში ან სააღრიცხვო სისტემაში შეაქვს, მაგალითად 1C‑ში ან SAP‑ში. ის დოკუმენტებს ერთმანეთს ადარებს და შეუსაბამობებს მონიშნავს, მაგალითად წონას ინვოისსა და შეფუთვის სიაში. კლიენტებს კითხვაზე „სად არის ჩემი ტვირთი“ WhatsApp‑სა და Telegram‑ში თქვენი სისტემის მონაცემებით პასუხობს, მძღოლებს კი დოკუმენტებსა და მარშრუტში ეხმარება. დეკლარაციებს AI არ აგზავნის: სადავო მონაცემებს თანამშრომელი ადასტურებს. მზა ინსტრუმენტების დანერგვა თქვენს დოკუმენტბრუნვაზე — 3 200 ₾‑დან, შემუშავება TMS‑თან, 1C‑სთან ან ERP‑სთან ინტეგრაციით — 6 700 ₾‑დან, მხარდაჭერა — 550 ₾‑დან თვეში. პილოტი დოკუმენტების ერთ ნაკადზე 2–4 კვირა გრძელდება. შედეგს ვზომავთ დამუშავების დროითა და მონაცემების ხელით გადატანის რაოდენობით.']
 },
 manufacturing:{
  q:['Что ИИ делает на производстве и сколько это стоит?','What does AI do in manufacturing, and what does it cost?','რას აკეთებს AI წარმოებაში და რა ღირს?'],
  a:['ИИ-ассистент отвечает инженерам, мастерам и операторам по вашим инструкциям, спецификациям, регламентам охраны труда и архиву ремонтов. Каждый ответ он сопровождает ссылкой на конкретный раздел утверждённого документа. Он помогает найти порядок обслуживания оборудования, проверить допуск к работам и подготовить заявку на запчасти или сырьё по данным вашей системы, например SAP или 1С. Доступен он в цеху с телефона или в Microsoft Teams. Решение всегда остаётся за инженером, а вариант размещения, вплоть до серверов на вашей площадке, подбираем под требования к секретности. Внедрение ассистента на ваших документах — от 3 200 ₾, разработка с интеграцией в ERP — от 6 700 ₾, сопровождение — от 550 ₾ в месяц. Пилот на одном участке занимает 2–4 недели. Результат измеряем по времени поиска и точности найденной информации.',
   'An AI assistant answers engineers, supervisors and operators from your instructions, specifications, safety rules and maintenance archive, and every answer links to the exact section of an approved document. It helps find equipment maintenance procedures, check work permits and prepare requests for spare parts or materials from your system data, for example SAP or 1C. Staff reach it on the shop floor from a phone or in Microsoft Teams. The engineer always makes the decision, and we choose the hosting option, up to servers on your premises, to match your confidentiality requirements. Implementing the assistant on your documents starts at 3,200 ₾, custom development with ERP integration at 6,700 ₾, and support at 550 ₾ a month. A pilot in one area takes 2–4 weeks. We measure search time and retrieval accuracy.',
   'AI ასისტენტი ინჟინრებს, ოსტატებსა და ოპერატორებს თქვენი ინსტრუქციებით, სპეციფიკაციებით, შრომის უსაფრთხოების წესებითა და რემონტების არქივით პასუხობს. თითოეულ პასუხს დამტკიცებული დოკუმენტის კონკრეტულ ნაწილზე ბმულით ახლავს. ის ეხმარება აღჭურვილობის მომსახურების წესის პოვნაში, სამუშაოებზე დაშვების შემოწმებასა და სათადარიგო ნაწილების ან ნედლეულის მოთხოვნის მომზადებაში თქვენი სისტემის მონაცემებით, მაგალითად SAP‑იდან ან 1C‑იდან. საამქროში ის ტელეფონიდან ან Microsoft Teams‑ში ხელმისაწვდომია. გადაწყვეტილება ყოველთვის ინჟინერთან რჩება, განთავსების ვარიანტს კი, თქვენს ტერიტორიაზე სერვერების ჩათვლით, საიდუმლოების მოთხოვნებზე ვარჩევთ. ასისტენტის დანერგვა თქვენს დოკუმენტებზე — 3 200 ₾‑დან, შემუშავება ERP‑სთან ინტეგრაციით — 6 700 ₾‑დან, მხარდაჭერა — 550 ₾‑დან თვეში. პილოტი ერთ უბანზე 2–4 კვირა გრძელდება. შედეგს ვზომავთ ძიების დროითა და ნაპოვნი ინფორმაციის სიზუსტით.']
 },
 services:{
  q:['Что ИИ делает для агентства или консалтинга и сколько это стоит?','What does AI do for an agency or consultancy, and what does it cost?','რას აკეთებს AI სააგენტოსთვის ან საკონსულტაციო კომპანიისთვის და რა ღირს?'],
  a:['ИИ превращает запись звонка с клиентом в протокол, бриф и задачи для команды в вашем трекере, например Jira, Asana, Notion или Bitrix24. По брифу он готовит черновик коммерческого предложения и договора на основе ваших шаблонов и прошлых проектов, а база знаний компании отвечает сотрудникам по кейсам, ценам и регламентам. Так команда тратит меньше неоплачиваемых часов на пресейл. Конфиденциальную информацию клиентов обрабатываем по согласованным правилам доступа и размещения, финальную вычитку документов делает специалист. Внедрение готовых инструментов под ваш процесс — от 3 200 ₾, разработка с интеграциями — от 6 700 ₾, обучение команды — от 1 900 ₾, сопровождение — от 550 ₾ в месяц. Пилот на одном процессе занимает 2–4 недели. Результат измеряем по времени подготовки предложения и числу уточнений.',
   'AI turns a recording of a client call into minutes, a brief and tasks for the team in your tracker, for example Jira, Asana, Notion or Bitrix24. From the brief it drafts a proposal and contract using your templates and past projects, and a company knowledge base answers staff questions about cases, rates and procedures. The team spends fewer unpaid hours on presales. Client confidential information is handled under agreed access and hosting rules, and a specialist does the final review of documents. Implementing ready tools for your process starts at 3,200 ₾, custom development with integrations at 6,700 ₾, team training at 1,900 ₾, and support at 550 ₾ a month. A pilot on one workflow takes 2–4 weeks. We measure proposal preparation time and the number of clarification rounds.',
   'AI კლიენტთან ზარის ჩანაწერს ოქმად, ბრიფად და გუნდის ამოცანებად აქცევს თქვენს ტრეკერში, მაგალითად Jira‑ში, Asana‑ში, Notion‑სა ან Bitrix24‑ში. ბრიფით ის კომერციული შეთავაზებისა და ხელშეკრულების მონახაზს თქვენი შაბლონებითა და წინა პროექტებით ამზადებს, კომპანიის ცოდნის ბაზა კი თანამშრომლებს ქეისებზე, ფასებსა და წესებზე პასუხობს. ასე გუნდი პრესეილზე ნაკლებ აუნაზღაურებელ საათს ხარჯავს. კლიენტების კონფიდენციალურ ინფორმაციას შეთანხმებული წვდომისა და განთავსების წესებით ვამუშავებთ, დოკუმენტების საბოლოო შემოწმებას სპეციალისტი აკეთებს. მზა ინსტრუმენტების დანერგვა თქვენს პროცესზე — 3 200 ₾‑დან, შემუშავება ინტეგრაციებით — 6 700 ₾‑დან, გუნდის სწავლება — 1 900 ₾‑დან, მხარდაჭერა — 550 ₾‑დან თვეში. პილოტი ერთ პროცესზე 2–4 კვირა გრძელდება. შედეგს ვზომავთ შეთავაზების მომზადების დროითა და დაზუსტებების რაოდენობით.']
 },
 education:{
  q:['Что ИИ делает для школы или курсов и сколько это стоит?','What does AI do for a school or course provider, and what does it cost?','რას აკეთებს AI სკოლისთვის ან კურსებისთვის და რა ღირს?'],
  a:['ИИ-ассистент в Telegram, WhatsApp, Instagram и на сайте помогает выбрать программу и тариф, отвечает о расписании, ценах и условиях договора и записывает на пробное занятие на грузинском, английском или русском. Заявки он передаёт в CRM, например в amoCRM или AlfaCRM. Студентам бот-куратор напоминает о дедлайнах и отвечает на типовые вопросы по курсу, а преподавателю помогает проверять задания по вашим критериям. Спорные оценки остаются за преподавателем. Ассистент отвечает только по вашим программам и договору и не обещает того, чего нет в оферте. Внедрение одного сценария с интеграцией в вашу систему стоит от 3 200 ₾, платформа и сопровождение по желанию — от 550 ₾ в месяц. Пилот в сезон набора занимает 2–4 недели. Результат измеряем по времени ответа и полноте заявок на обучение.',
   'An AI assistant on Telegram, WhatsApp, Instagram and your website helps prospective students choose a programme and plan, answers questions about schedules, prices and contract terms, and books trial lessons in Georgian, English or Russian. It passes applications to your CRM, for example amoCRM or AlfaCRM. For students, a curator bot reminds them about deadlines and answers routine course questions, and for teachers it helps check assignments against your criteria, with disputed grades left to the teacher. The assistant answers only from your programmes and contract and never promises what is not in the offer. Implementing one workflow integrated with your system starts at 3,200 ₾, with optional platform and support from 550 ₾ a month. A pilot during enrolment takes 2–4 weeks. We measure response time and application completeness.',
   'AI ასისტენტი Telegram‑ში, WhatsApp‑ში, Instagram‑სა და საიტზე პროგრამისა და ტარიფის არჩევაში ეხმარება, პასუხობს განრიგზე, ფასებსა და ხელშეკრულების პირობებზე და საცდელ გაკვეთილზე წერს ქართულად, ინგლისურად ან რუსულად. მოთხოვნებს CRM‑ში გადასცემს, მაგალითად amoCRM‑ში ან AlfaCRM‑ში. სტუდენტებს ბოტი‑კურატორი ვადებს შეახსენებს და კურსზე ტიპურ კითხვებს პასუხობს, მასწავლებელს კი დავალებების თქვენი კრიტერიუმებით შემოწმებაში ეხმარება. სადავო შეფასებები მასწავლებელთან რჩება. ასისტენტი მხოლოდ თქვენი პროგრამებითა და ხელშეკრულებით პასუხობს და არ ჰპირდება იმას, რაც ოფერტაში არ არის. ერთი სცენარის დანერგვა თქვენს სისტემასთან ინტეგრაციით ღირს 3 200 ₾‑დან, პლატფორმა და მხარდაჭერა სურვილისამებრ — 550 ₾‑დან თვეში. პილოტი მიღების სეზონში 2–4 კვირა გრძელდება. შედეგს ვზომავთ პასუხის დროითა და სწავლის მოთხოვნების სისრულით.']
 },
};
