// praxenai.ge blog: topics for companies in Georgia, different from the praxenai.com blog (Adjara hotels, WhatsApp and Telegram bots).
// Russian and English versions; the Georgian list links to them until a native speaker has proofread a translation.
// Prices come from lib/pricing.ts; no third-party statistics.
import type {Lang} from '@/lib/content';
import {money,prices} from '@/lib/pricing';

export type GeBlock={h:string;p?:string[];list?:string[];table?:[string[],...string[][]]};
export type GePost={cat:string;title:string;description:string;excerpt:string;dateLabel:string;minutes:number;answer:string;blocks:GeBlock[];faq:[string,string][];links:[string,string][]};
export type GeArticle={slug:string;date:string;langs:Partial<Record<Lang,GePost>>};

const gel=(k:keyof typeof prices)=>money(prices[k],'gel'),usd=(k:keyof typeof prices)=>money(prices[k],'usd');
const tr=gel('training'),im=gel('implementation'),dev=gel('development'),sup=gel('support');

export const geArticles:GeArticle[]=[
 {slug:'ai-for-hotels-adjara',date:'2026-10-08',langs:{
  ru:{cat:'Отели',dateLabel:'8 октября 2026',minutes:7,
   title:'ИИ для отелей в Аджарии: что автоматизировать до сезона 2027',
   description:'Что поручить ИИ в отеле в Батуми или Кобулети до следующего сезона: ответы гостям, брони, трансферы, отзывы. План по месяцам, цены в лари и пример расчёта.',
   excerpt:'Ответы гостям, брони и отзывы: план до сезона по месяцам, цены в лари и пример расчёта.',
   answer:'Отелю в Аджарии стоит начать с ответов гостям в WhatsApp и Instagram на грузинском, русском и английском, затем подключить брони, трансферы и отзывы. Межсезонье с октября по апрель — лучшее время для пилота: персонал свободнее, а результат проверится на весенних бронированиях. Внедрение у Praxen AI стоит от '+im+', пилот на одном процессе занимает от 2 недель.',
   blocks:[
    {h:'Почему начинать в межсезонье',p:['Летом администратор отвечает на десятки сообщений в день, и на настройку нового инструмента нет времени. С октября по апрель поток ниже: можно спокойно собрать базу знаний, проверить бота на реальных вопросах и обучить персонал. К маю решение уже работает, а вы сравниваете показатели с прошлым сезоном.']},
    {h:'Что поручить ИИ в первую очередь',list:['Ответы гостям в WhatsApp, Instagram и на сайте: цены по датам, трансфер из аэропорта, парковка, завтрак, заселение с животными. На том языке, на котором пишет гость.','Запросы на бронирование: бот уточняет даты, число гостей и пожелания и передаёт готовую заявку администратору или в систему бронирования, если она это поддерживает.','Трансферы, экскурсии и допуслуги: бот предлагает их перед заездом и собирает заявки.','Напоминания и инструкции: время заезда, как добраться, код от двери или парковки.','Отзывы: черновики ответов на Google и Booking.com в тоне вашего отеля, отправляет сотрудник.']},
    {h:'План до сезона по месяцам',table:[['Когда','Что делаем'],['Октябрь–ноябрь','Бесплатный аудит, выбор первого процесса, сбор цен и ответов на частые вопросы'],['Декабрь–январь','Пилот: бот отвечает на реальные сообщения, администратор проверяет ответы'],['Февраль–март','Донастройка, подключение броней и допуслуг, обучение персонала'],['Апрель–май','Работа в сезоне и замеры: время ответа, число броней из переписки, нагрузка на администратора']]},
    {h:'Сколько это стоит',table:[['Формат','Цена'],['Чат-бот с базой знаний и передачей броней администратору','от '+im+' ('+usd('implementation')+')'],['Интеграция с системой бронирования, сложная логика цен','от '+dev+' ('+usd('development')+')'],['Обучение персонала','от '+tr+' ('+usd('training')+')'],['Ведение в сезон: обновление цен и проверка ответов','от '+sup+' в месяц, по желанию']],p:['Токены ИИ и сообщения WhatsApp оплачиваются провайдерам напрямую, на вашем аккаунте. Аудит бесплатный, цену пилота фиксируем до старта.']},
    {h:'Пример расчёта для отеля на 40 номеров',p:['Цифры условные, ваши считаем на аудите. Летом администратор отвечает на 30–50 сообщений в день, часть ночных сообщений остаётся без ответа до утра.','Если бот берёт на себя около 60% вопросов, администратор освобождает примерно 2 часа в день, или 60 часов в месяц. При стоимости часа около 10 ₾ это 600 ₾ в месяц. К этому добавляются ночные брони, которые раньше уходили к конкурентам. По одному сэкономленному времени запуск от '+im+' окупается примерно за полгода работы в сезон.']},
    {h:'Что подготовить к аудиту',list:['Цены по сезонам и правила отмены.','Список вопросов, которые гости задают чаще всего, можно просто выгрузку переписки за прошлый сезон.','Условия трансфера, экскурсий и других услуг с ценами.','Кто из сотрудников принимает брони и в каком канале.']},
   ],
   faq:[['Будет ли бот сам подтверждать бронь?','По умолчанию бот собирает заявку и передаёт её администратору. Подтверждать бронь сам он может, только если ваша система бронирования это позволяет и вы это разрешили.'],['На каких языках бот отвечает гостям?','На грузинском, русском и английском, а при необходимости и на других языках ваших гостей. Качество проверяем на реальных сообщениях до запуска.'],['Что, если гость недоволен или вопрос нестандартный?','Бот сразу передаёт диалог администратору вместе со всей перепиской.']],
   links:[['industries/hotels','ИИ для отелей'],['industries/tourism','ИИ для туризма'],['solutions','Все форматы и цены']]},
  en:{cat:'Hotels',dateLabel:'8 October 2026',minutes:7,
   title:'AI for hotels in Adjara: what to automate before the 2027 season',
   description:'What a hotel in Batumi or Kobuleti can hand to AI before next season: guest replies, bookings, transfers and reviews. A month-by-month plan, prices in lari and a worked example.',
   excerpt:'Guest replies, bookings and reviews: a month-by-month plan, prices in lari and a worked example.',
   answer:'A hotel in Adjara should start with guest replies on WhatsApp and Instagram in Georgian, Russian and English, then add bookings, transfers and reviews. The off-season from October to April is the best time for a pilot: staff have more time, and the result is tested on spring bookings. With Praxen AI, implementation costs from '+im+' and a pilot on one workflow takes from 2 weeks.',
   blocks:[
    {h:'Why start in the off-season',p:['In summer the front desk answers dozens of messages a day and has no time to set up a new tool. From October to April the flow is lower: there is time to build the knowledge base, test the bot on real questions and train staff. By May it is working, and you can compare the numbers with last season.']},
    {h:'What to hand to AI first',list:['Guest replies on WhatsApp, Instagram and your website: prices by date, airport transfers, parking, breakfast, pets. In the language the guest writes in.','Booking requests: the bot checks dates, number of guests and wishes, then passes a complete request to the front desk, or to your booking system if it supports this.','Transfers, tours and extras: the bot offers them before arrival and collects requests.','Reminders and instructions: check-in time, directions, door or parking codes.','Reviews: draft replies on Google and Booking.com in your hotel’s tone, sent by a member of staff.']},
    {h:'Month-by-month plan',table:[['When','What happens'],['October–November','Free audit, choosing the first workflow, collecting prices and common answers'],['December–January','Pilot: the bot answers real messages and the front desk checks its replies'],['February–March','Fine-tuning, adding bookings and extras, staff training'],['April–May','Live in season, with measurement: reply time, bookings from chats and front-desk workload']]},
    {h:'What it costs',table:[['Format','Price'],['Chatbot with a knowledge base and booking handover to the front desk','from '+im+' ('+usd('implementation')+')'],['Integration with your booking system, complex pricing logic','from '+dev+' ('+usd('development')+')'],['Staff training','from '+tr+' ('+usd('training')+')'],['Maintenance in season: price updates and answer reviews','from '+sup+' a month, optional']],p:['AI tokens and WhatsApp messages are paid directly to the providers, on your account. The audit is free, and we fix the pilot price before work starts.']},
    {h:'Worked example: a 40-room hotel',p:['The figures are illustrative; we work out yours in the audit. In summer the front desk answers 30–50 messages a day, and some night-time messages wait until morning.','If the bot handles about 60% of questions, the front desk gains roughly 2 hours a day, or 60 hours a month. At about 10 ₾ an hour that is 600 ₾ a month, plus the night-time bookings that used to go to competitors. On time saved alone, a launch from '+im+' pays back in about six months of the season.']},
    {h:'What to prepare for the audit',list:['Prices by season and the cancellation policy.','The questions guests ask most; an export of last season’s chats is enough.','Terms and prices for transfers, tours and other extras.','Who takes bookings, and in which channel.']},
   ],
   faq:[['Will the bot confirm bookings itself?','By default it collects the request and passes it to the front desk. It confirms bookings itself only if your booking system allows it and you approve it.'],['Which languages does it use with guests?','Georgian, Russian and English, and other languages your guests use if needed. We check quality on real messages before launch.'],['What if a guest is unhappy or the question is unusual?','The bot hands the conversation to the front desk straight away, with the full chat history.']],
   links:[['industries/hotels','AI for hotels'],['industries/tourism','AI for tourism'],['solutions','All formats and prices']]},
 }},
 {slug:'whatsapp-telegram-ai-chatbot',date:'2026-10-08',langs:{
  ru:{cat:'Чат-боты',dateLabel:'8 октября 2026',minutes:6,
   title:'Чат-бот с ИИ для WhatsApp и Telegram: что умеет и сколько стоит',
   description:'Что умеет чат-бот с ИИ, чем отличаются WhatsApp и Telegram, сколько стоит внедрение в Грузии и как проверить подрядчика.',
   excerpt:'Возможности, разница между WhatsApp и Telegram, цены в лари и чек-лист для выбора подрядчика.',
   answer:'Чат-бот с ИИ для WhatsApp или Telegram отвечает клиентам по вашей базе знаний на грузинском, русском и английском, записывает заявки в CRM и передаёт сложные вопросы сотруднику. В Praxen AI внедрение стоит от '+im+', запуск пилота — от 2 недель. Telegram-бот подключается бесплатно. WhatsApp работает через WhatsApp Business API от Meta: ответы клиенту бесплатны, шаблонные сообщения оплачиваются по тарифу Meta.',
   blocks:[
    {h:'Что умеет чат-бот с ИИ',list:['Отвечает на вопросы о ценах, услугах, наличии и сроках по вашей базе знаний, а не по общим данным из интернета.','Записывает на услугу или принимает бронь и сразу показывает свободное время.','Задаёт уточняющие вопросы и записывает заявку в amoCRM, Bitrix24 или таблицу.','Передаёт диалог сотруднику с полной историей, если вопрос сложный или клиент недоволен.','Отвечает на грузинском, русском и английском: на том языке, на котором пишет клиент.']},
    {h:'WhatsApp или Telegram',table:[['','WhatsApp','Telegram'],['Подключение','Через WhatsApp Business API от Meta, нужна проверка компании','Через @BotFather за несколько минут'],['Сообщения','Ответы в течение 24 часов после сообщения клиента бесплатны, шаблонные сообщения платные','Бесплатно'],['Рассылки','Только по одобренным шаблонам и клиентам, давшим согласие','Только тем, кто запустил бота'],['Интерфейс','Текст, кнопки и списки','Текст, кнопки, меню и мини-приложения']],p:['Выбирайте канал, в котором вам уже пишут клиенты. Один бот может работать сразу в обоих каналах и на сайте с общей базой знаний.']},
    {h:'Сколько стоит',table:[['Что нужно','Цена'],['Бот на готовой платформе с базой знаний и записью заявок в CRM','от '+im],['Сложная логика, интеграция с 1С или системой отеля, свой интерфейс','от '+dev],['Ведение: обновление базы знаний и проверка ответов','от '+sup+' в месяц, по желанию'],['Токены ИИ и сообщения WhatsApp','по тарифам провайдеров, на вашем аккаунте']]},
    {h:'Как проходит запуск',list:['Бесплатный аудит: смотрим, какие вопросы приходят чаще всего и где теряются заявки.','База знаний: собираем цены, ответы и правила, что бот может говорить, а что передаёт сотруднику.','Настройка и интеграции: подключаем канал, CRM и календарь.','Тест: проверяем бота на ваших реальных вопросах на всех трёх языках.','Запуск и замеры: сравниваем время ответа и число заявок с тем, что было до бота.']},
    {h:'Как проверить подрядчика',list:['Бот отвечает только по вашей базе знаний и честно говорит, когда не знает ответа.','Есть передача диалога сотруднику и журнал всех переписок.','Бот и данные работают на ваших аккаунтах, а не на аккаунте подрядчика.','Качество ответов на грузинском проверяют на ваших примерах до запуска.','Цену пилота и метрику успеха фиксируют до начала работ.']},
   ],
   faq:[['Будет ли бот выдумывать ответы?','Мы настраиваем его отвечать только по вашей базе знаний. Если ответа там нет, бот говорит об этом и передаёт вопрос сотруднику.'],['Можно ли подключить Instagram и Facebook?','Да, через API Meta. Бот отвечает в Direct и Messenger по той же базе знаний.'],['Сколько времени занимает запуск?','Пилот на одном канале — от 2 недель, включая тесты на ваших вопросах.']],
   links:[['departments/support','ИИ для поддержки клиентов'],['departments/sales','ИИ для продаж'],['solutions','Цены']]},
  en:{cat:'Chatbots',dateLabel:'8 October 2026',minutes:6,
   title:'AI chatbot for WhatsApp and Telegram: what it does and what it costs',
   description:'What an AI chatbot can do, how WhatsApp and Telegram differ, what it costs in Georgia and how to check a provider.',
   excerpt:'Features, WhatsApp versus Telegram, prices in lari and a checklist for choosing a provider.',
   answer:'An AI chatbot for WhatsApp or Telegram answers customers from your knowledge base in Georgian, Russian and English, logs enquiries in your CRM and passes difficult questions to a person. With Praxen AI, implementation costs from '+im+' and a pilot launches in 2 weeks or more. A Telegram bot is free to connect. WhatsApp runs through Meta’s WhatsApp Business API: replies to customers are free, and template messages are charged at Meta’s rates.',
   blocks:[
    {h:'What an AI chatbot does',list:['Answers questions about prices, services, availability and timing from your knowledge base, not from general internet data.','Books a service or a room and shows free slots straight away.','Asks follow-up questions and logs the enquiry in amoCRM, Bitrix24 or a spreadsheet.','Hands the conversation to a person with the full history when the question is complex or the customer is unhappy.','Replies in Georgian, Russian and English, in the language the customer writes in.']},
    {h:'WhatsApp or Telegram',table:[['','WhatsApp','Telegram'],['Set-up','Through Meta’s WhatsApp Business API, with business verification','Through @BotFather in a few minutes'],['Messages','Replies within 24 hours of a customer’s message are free; template messages are charged','Free'],['Broadcasts','Only approved templates, to customers who opted in','Only to people who started the bot'],['Interface','Text, buttons and lists','Text, buttons, menus and mini apps']],p:['Choose the channel your customers already use. One bot can work in both channels and on your website with a shared knowledge base.']},
    {h:'What it costs',table:[['What you need','Price'],['A bot on an existing platform with a knowledge base and CRM logging','from '+im],['Complex logic, integration with 1C or a hotel system, a custom interface','from '+dev],['Maintenance: knowledge base updates and answer reviews','from '+sup+' a month, optional'],['AI tokens and WhatsApp messages','at provider rates, on your account']]},
    {h:'How the launch works',list:['Free audit: we look at the most common questions and where enquiries get lost.','Knowledge base: we collect prices, answers and rules on what the bot may say and what it passes to a person.','Set-up and integrations: we connect the channel, CRM and calendar.','Testing: we check the bot on your real questions in all three languages.','Launch and measurement: we compare reply time and enquiries with how things ran before the bot.']},
    {h:'How to check a provider',list:['The bot answers only from your knowledge base and says so when it does not know.','There is a handover to a person and a log of every conversation.','The bot and data run on your accounts, not the provider’s.','Answer quality in Georgian is tested on your examples before launch.','The pilot price and success metric are fixed before work starts.']},
   ],
   faq:[['Will the bot make up answers?','We set it up to answer only from your knowledge base. If the answer is not there, the bot says so and passes the question to a person.'],['Can it work in Instagram and Facebook?','Yes, through Meta’s API. The bot answers in Direct and Messenger from the same knowledge base.'],['How long does launch take?','A pilot on one channel takes from 2 weeks, including tests on your questions.']],
   links:[['departments/support','AI for customer support'],['departments/sales','AI for sales'],['solutions','Prices']]},
 }},
];

export const geArticle=(slug:string)=>geArticles.find(a=>a.slug===slug);
export const geBlogUpdated='2026-10-08';
