// praxenai.ge: questions that belong to one list or company page each, so FAQ blocks do not repeat between pages.
// Facts match the page copy (pricing, security, about); no promises beyond it.
import type {C} from './site-copy';
import {money,prices} from './pricing';

type QA=[string,string];

export function geFaq(c:C){
 const sup=money(prices.support,'gel'),supUsd=money(prices.support,'usd');
 const qa=(q:[string,string,string],a:[string,string,string]):QA=>[c(...q),c(...a)];
 return {
  excluded:qa(['Что не входит в цену внедрения?','What is not included in the implementation price?','რა არ შედის დანერგვის ფასში?'],
   ['Токены ИИ, серверы и платные сообщения WhatsApp. Они оплачиваются поставщикам напрямую, на ваших аккаунтах, без нашей наценки. На аудите оцениваем, сколько это будет стоить в месяц при вашем объёме.','AI tokens, servers and paid WhatsApp messages. You pay the providers directly, on your own accounts, with no mark-up from us. In the audit we estimate the monthly cost for your volume.','AI ტოკენები, სერვერები და ფასიანი WhatsApp შეტყობინებები. მათ პირდაპირ პროვაიდერებს უხდით, თქვენს ანგარიშებზე, ჩვენი ფასნამატის გარეშე. აუდიტზე ვაფასებთ, რა დაჯდება ეს თვეში თქვენი მოცულობით.']),
  support:qa(['Обязательно ли ежемесячное ведение?','Is monthly maintenance required?','სავალდებულოა ყოველთვიური მომსახურება?'],
   ['Нет. Ведение по желанию, от '+sup+' ('+supUsd+') в месяц: обновляем базу знаний, проверяем ответы и исправляем ошибки. Решение работает на ваших аккаунтах и без него.','No. Maintenance is optional, from '+sup+' ('+supUsd+') a month: we update the knowledge base, review answers and fix issues. The solution keeps running on your accounts without it.','არა. მომსახურება არჩევითია, '+sup+'‑დან ('+supUsd+') თვეში: ვაახლებთ ცოდნის ბაზას, ვამოწმებთ პასუხებს და ვასწორებთ შეცდომებს. გადაწყვეტა მის გარეშეც მუშაობს თქვენს ანგარიშებზე.']),
  pilotPrice:qa(['Когда фиксируется цена пилота?','When is the pilot price fixed?','როდის ფიქსირდება პილოტის ფასი?'],
   ['После бесплатного аудита, до начала работ. В предложении указаны процесс, сроки, цена и метрика, по которой проверяем результат.','After the free audit and before work starts. The proposal names the workflow, timeline, price and the metric we use to check the result.','უფასო აუდიტის შემდეგ, სამუშაოს დაწყებამდე. შეთავაზებაში მითითებულია პროცესი, ვადები, ფასი და მეტრიკა, რომლითაც შედეგს ვამოწმებთ.']),
  trainingHow:qa(['Как проходит обучение?','How does the training work?','როგორ მიმდინარეობს სწავლება?'],
   ['На задачах вашей команды: документах, обращениях, контенте и данных. Сотрудники уходят с рабочими шаблонами и правилами работы с ИИ. Программу и длительность согласуем после короткого разговора.','On your team’s own tasks: documents, enquiries, content and data. People leave with working templates and rules for using AI. We agree the programme and length after a short call.','თქვენი გუნდის ამოცანებზე: დოკუმენტებზე, მოთხოვნებზე, კონტენტსა და მონაცემებზე. თანამშრომლები იღებენ სამუშაო შაბლონებს და AI‑ით მუშაობის წესებს. პროგრამასა და ხანგრძლივობას მოკლე საუბრის შემდეგ ვათანხმებთ.']),
  trainingLang:qa(['На каком языке проходит обучение?','Which language is the training in?','რა ენაზე მიმდინარეობს სწავლება?'],
   ['На русском или английском. Обучение на грузинском согласуем отдельно.','Russian or English. Training in Georgian is agreed separately.','რუსულ ან ინგლისურ ენაზე. ქართულ ენაზე სწავლებას ცალკე ვათანხმებთ.']),
  casesReal:qa(['Это реальные кейсы клиентов?','Are these real client cases?','ეს კლიენტების რეალური ქეისებია?'],
   ['Нет, это примеры сценариев с типичными цифрами. Они показывают, как устроено решение и что мы измеряем. Результат для вашей компании считаем на аудите и проверяем в пилоте.','No. They are example scenarios with typical figures. They show how a solution works and what we measure. We estimate the result for your company in the audit and check it in the pilot.','არა, ეს სცენარების მაგალითებია ტიპური ციფრებით. ისინი აჩვენებს, როგორ მუშაობს გადაწყვეტა და რას ვზომავთ. თქვენი კომპანიის შედეგს აუდიტზე ვითვლით და პილოტში ვამოწმებთ.']),
  measure:qa(['Как вы измеряете результат?','How do you measure the result?','როგორ ზომავთ შედეგს?'],
   ['До старта выбираем одну метрику: время ответа, часы ручной работы или долю заявок, дошедших до сделки. Замеряем её до запуска и после, на одних и тех же типах данных.','Before we start, we choose one metric: reply time, hours of manual work, or the share of enquiries that reach a deal. We measure it before and after launch, on the same kind of data.','დაწყებამდე ვირჩევთ ერთ მეტრიკას: პასუხის დროს, ხელით მუშაობის საათებს ან გარიგებამდე მისული მოთხოვნების წილს. მას ვზომავთ გაშვებამდე და მის შემდეგ, ერთი და იმავე ტიპის მონაცემებზე.']),
  notListed:qa(['Нашей отрасли нет в списке. Сможете помочь?','Our industry is not listed. Can you help?','ჩვენი ინდუსტრია სიაში არ არის. დაგვეხმარებით?'],
   ['Да. Отраслевые страницы показывают частые сценарии, а работаем мы с вашим процессом: заявками, документами, ответами клиентам. На аудите разбираем ваш случай.','Yes. The industry pages show common scenarios, and the work itself is about your workflow: enquiries, documents and replies to customers. We look at your case in the audit.','დიახ. ინდუსტრიების გვერდებზე ხშირი სცენარებია, ჩვენ კი ვმუშაობთ თქვენს პროცესზე: მოთხოვნებზე, დოკუმენტებსა და კლიენტებისთვის პასუხებზე. თქვენს შემთხვევას აუდიტზე განვიხილავთ.']),
  who:qa(['Кто будет работать над проектом?','Who will work on our project?','ვინ იმუშავებს ჩვენს პროექტზე?'],
   ['Один ответственный ведёт проект от аудита до запуска: разбирает процесс, настраивает решение и проверяет его на ваших данных. Связь напрямую в WhatsApp или Telegram.','One accountable lead runs the project from audit to launch: maps the workflow, sets up the solution and tests it on your data. You reach them directly on WhatsApp or Telegram.','პროექტს აუდიტიდან გაშვებამდე ერთი პასუხისმგებელი პირი უძღვება: არჩევს პროცესს, აწყობს გადაწყვეტას და ამოწმებს მას თქვენს მონაცემებზე. მასთან პირდაპირ დაკავშირდებით WhatsApp‑ით ან Telegram‑ით.']),
  onSite:qa(['Работаете ли вы очно?','Do you work on site?','ადგილზე მუშაობთ?'],
   ['Да. Мы находимся в Батуми и работаем с компаниями в Тбилиси и по всей Грузии, очно и удалённо.','Yes. We are based in Batumi and work with companies in Tbilisi and across Georgia, on site and remotely.','დიახ. ვართ ბათუმში და ვმუშაობთ კომპანიებთან თბილისსა და მთელ საქართველოში, ადგილზე და დისტანციურად.']),
  dataTraining:qa(['Используются ли наши данные для обучения ИИ?','Is our data used to train AI?','გამოიყენება ჩვენი მონაცემები AI‑ის სწავლებისთვის?'],
   ['Нет. Мы работаем через корпоративные API OpenAI и Anthropic: по их условиям данные не используются для обучения публичных моделей.','No. We use the OpenAI and Anthropic enterprise APIs, and under their terms your data is not used to train public models.','არა. ვმუშაობთ OpenAI‑სა და Anthropic‑ის კორპორაციული API‑ებით: მათი პირობებით მონაცემები საჯარო მოდელების სწავლებისთვის არ გამოიყენება.']),
  whoSees:qa(['Кто видит переписку и документы?','Who can see conversations and documents?','ვინ ხედავს მიმოწერასა და დოკუმენტებს?'],
   ['Ваши сотрудники, по ролям, которые вы задаёте. У нас доступ есть только на время работ, после передачи проекта его отзывают.','Your staff, by the roles you set. We have access only while we work on the project, and it is removed after handover.','თქვენი თანამშრომლები, თქვენ მიერ განსაზღვრული როლების მიხედვით. ჩვენ წვდომა მხოლოდ სამუშაოს დროს გვაქვს და პროექტის გადაცემის შემდეგ უქმდება.']),
 };
}
