// praxenai.com blog. Articles from docs/CONTENT-PLAN.md (clusters E1–E4), British English.
// Numbers come from our own prices (lib/intl.ts) and the reader's own figures; no third-party statistics.
import {fmt,price,promo,curInfo} from '@/lib/intl';

export type Block={h:string;p?:string[];list?:string[];table?:[string[],...string[][]]};
export type Post={slug:string;cat:string;title:string;description:string;excerpt:string;date:string;dateLabel:string;minutes:number;answer:string;blocks:Block[];faq:[string,string][];links:[string,string][]};

const rcSetup=fmt(price('rcSetup')),rcMonth=fmt(price('rcMonth')),rcSetupP=fmt(promo(price('rcSetup'))),rcMonthP=fmt(promo(price('rcMonth')));
const pilot=fmt(price('pilot')),pilotP=fmt(promo(price('pilot'))),custom=fmt(price('custom')),customP=fmt(promo(price('custom')));
const training=fmt(price('training')),trainingP=fmt(promo(price('training'))),care=fmt(price('care')),careP=fmt(promo(price('care')));
const usage=curInfo.gbp.usage;

export const posts:Post[]=[
 {slug:'ai-receptionist-cost-uk',cat:'AI receptionist',date:'2026-10-07',dateLabel:'7 October 2026',minutes:7,
  title:'How much does an AI receptionist cost in the UK?',
  description:'Setup, monthly fee and call minutes explained, with a simple way to check whether an AI receptionist pays for itself in your business.',
  excerpt:'Setup, the monthly fee and call minutes, plus a five-minute way to check whether it pays back for you.',
  answer:'An AI receptionist usually costs a one-off setup fee, a monthly fee and call minutes billed by the telephony and AI providers. With Praxen that is '+rcSetup+' setup and '+rcMonth+' a month ('+rcSetupP+' and '+rcMonthP+' with the launch offer), plus typically '+usage+' per minute of calls on your own accounts. Prices exclude VAT.',
  blocks:[
   {h:'What you pay for',p:['There are three parts to the price, and it helps to keep them separate when you compare quotes.'],list:['Setup: we train the voice agent on your services, prices and FAQs and connect your calendar and CRM. Then we test it on real call types before it goes live.','Monthly fee: monitoring, updates when your prices or opening hours change, and a monthly review of calls.','Call minutes: what the telephony and AI providers charge per minute. With us these run on your own accounts at cost, so there is no mark-up and you can see every call.']},
   {h:'Praxen prices',table:[['Item','Standard','Launch offer'],['Setup, one-off',rcSetup,rcSetupP],['Monthly fee',rcMonth+'/mo',rcMonthP+'/mo'],['Call minutes','typically '+usage+' a minute','at cost']],p:['All prices exclude VAT. Setup takes about two weeks. The monthly plan includes the review and updates; there is no charge per booking.']},
   {h:'What changes the price',list:['Number of call types. A clinic that books, moves and cancels appointments needs more testing than a firm that only takes messages.','Integrations. Google Calendar or Outlook are quick. A practice management system or a CRM with custom fields takes longer.','Languages. Each extra language is tested separately.','Call volume. Our fee stays the same; the minutes you pay the providers grow with it.']},
   {h:'How to check it pays back',p:['Use your own numbers from a normal week.'],list:['Count the calls you miss or send to voicemail in a week. Your phone system or provider usually shows this.','Estimate how many of those callers would have become customers. One in five is a cautious starting point for new enquiries.','Multiply by the value of a first order or appointment.','Compare the monthly result with the monthly fee and minutes.']},
   {h:'A worked example',p:['A dental practice misses 15 calls a week at lunch and after 6 pm. Say one in five of those is a new patient worth £150 on the first visit. That is three patients and £450 a week, or roughly £1,900 a month. Against '+rcMonthP+' a month plus minutes, the receptionist pays for itself if it saves even a fraction of those calls. Your numbers will differ, which is why we start with a free 30-minute audit.']},
   {h:'What an AI receptionist will not do',list:['It will not give clinical, legal or financial advice. Those calls go to a person.','It will not quote prices, discounts or dates outside the rules you approve.','It does not replace your team. It answers when they cannot and hands over anything that needs judgement.']},
  ],
  faq:[['Can it use my existing phone number?','Yes. You forward your number to it after hours, when lines are busy, or all the time.'],['Is there a long contract?','The setup is a one-off fee and the plan is billed monthly.'],['What does a typical call cost in minutes?','A three-minute call at '+usage+' a minute costs well under 50p.']],
  links:[['services/ai-receptionist','AI receptionist: how it works and pricing'],['industries/clinics','AI for clinics and dentists'],['solutions','All prices']]},
 {slug:'ai-implementation-cost',cat:'Pricing',date:'2026-10-07',dateLabel:'7 October 2026',minutes:8,
  title:'How much does AI implementation cost?',
  description:'Training, a pilot on one workflow, custom agents and ongoing care: what each costs, how long it takes and how to keep the first project small.',
  excerpt:'Four formats, what each costs and how to start small enough to measure the result.',
  answer:'For most businesses, AI implementation starts with one of four formats: team training ('+training+', '+trainingP+' with the launch offer), a pilot on one workflow ('+pilot+', '+pilotP+'), a custom solution with AI agents (from '+custom+', '+customP+') and optional ongoing care ('+care+' a month, '+careP+'). AI usage is paid to the providers at cost. Prices exclude VAT.',
  blocks:[
   {h:'Start with one workflow',p:['The most expensive AI projects are the ones that try to change everything at once. A business gets better results from one workflow with a clear metric: calls answered, invoices entered, replies sent within a minute. Once that works, the next workflow reuses the same knowledge base, access rules and integrations, so it is cheaper and faster.']},
   {h:'The four formats',table:[['Format','What you get','Timeline','Price (launch offer)'],['Team training','Half-day session on your own tasks, prompt library, usage policy','From 1 week',trainingP],['Implementation pilot','One workflow on your real data, connected to your tools','2–4 weeks',pilotP],['Custom AI solution','AI agents, internal assistants, custom integrations','From 4 weeks','from '+customP],['Ongoing care','Monitoring, knowledge base updates, fixes','Monthly',careP+'/mo']]},
   {h:'What drives the cost',list:['Integrations. Reading and writing to HubSpot, Xero or a booking system is most of the work in a pilot.','Data quality. Clean price lists and policies are quick to load. Scattered documents need sorting first.','Approval points. Every place where a person must check the result needs a screen and a rule.','Volume and languages. More channels and languages mean more testing.']},
   {h:'Costs people forget',list:['AI and telephony usage. Billed by the providers per message or minute. With us it runs on your own accounts at cost.','Staff time in the pilot. Expect a few hours from the person who knows the workflow best.','Changes after launch. Prices, products and policies change; someone has to update the knowledge base. That is what ongoing care covers.']},
   {h:'How to keep the first project small',list:['Pick the workflow that eats the most hours each week.','Agree one metric and how you will measure it before the build starts.','Test on last month’s real cases before going live.','Decide in advance what the AI may never do on its own.']},
   {h:'Is it worth it?',p:['Take the hours a workflow costs each month and multiply them by the hourly cost of the people doing it. Then add the revenue from enquiries you lose today. If a pilot at '+pilotP+' pays back within a few months on those numbers, it is worth testing. The savings calculator on our pricing page does this sum for you.']},
  ],
  faq:[['Do we need new software?','Usually not. We connect to the tools you already use.'],['Who owns the solution?','You do. It runs on your accounts, and you keep the documentation at handover.'],['Can we start with training only?','Yes. Team training is a standalone format.']],
  links:[['solutions','Pricing and savings calculator'],['services/ai-automation','AI automation'],['services/ai-consultancy','AI consultancy']]},
 {slug:'ai-for-accounting-firms',cat:'Accounting',date:'2026-10-08',dateLabel:'8 October 2026',minutes:8,
  title:'AI for accounting firms: what to automate first',
  description:'Which accounting workflows to hand to AI first, in what order, what to keep with your team and how Making Tax Digital changes the workload.',
  excerpt:'Seven workflows in the order we would automate them, what stays with your accountants and what a first pilot costs.',
  answer:'An accounting firm gets the quickest return from AI on admin around the work: chasing client documents, reading and coding invoices, answering status questions and preparing deadline reminders. Accountants keep the review, the advice and anything that goes to HMRC. A pilot on one of these workflows takes 2–4 weeks and costs '+pilot+' ('+pilotP+' with the launch offer). Prices exclude VAT.',
  blocks:[
   {h:'Why the workload is growing',p:['Making Tax Digital for Income Tax started on 6 April 2026 for sole traders and landlords with qualifying income over £50,000. The threshold drops to £30,000 from April 2027. For a firm with these clients, one deadline a year becomes four quarterly updates plus the final declaration. That is four rounds of chasing records instead of one, and the same staff to do it.','AI will not do the accounting for you. It can take over the admin that surrounds each deadline, so the extra rounds do not land on your accountants’ evenings.']},
   {h:'The 7 workflows, in the order we would start',list:['Chasing missing documents. The system knows which client owes which records for which period and sends polite, specific reminders by email or WhatsApp, then escalates to a person after the second one.','Reading and coding invoices and receipts. Documents from email, uploads and photos are read, matched to the client and coded into Xero, QuickBooks or Sage as drafts. Your team approves them.','Answering “where is my return?” questions. A chat or phone assistant checks the status in your practice software and replies, or books a call with the right accountant.','Bank transaction matching. Unclear lines are grouped and sent to the client as one short list of questions instead of a dozen emails.','Onboarding new clients. The engagement letter, ID checks and the first document request go out in one sequence, with reminders until everything is in.','Preparing deadline reminders. Each client gets their own dates and their own list of what is still missing.','First drafts of routine letters and summaries. Year-end summaries and standard responses are drafted from your templates for an accountant to edit and sign.']},
   {h:'What stays with your accountants',list:['Advice, judgement calls and anything that changes a client’s tax position.','Submissions to HMRC and Companies House.','Payments and any change to supplier or client bank details. A request to change bank details is flagged as a fraud risk and goes to a person.','Final review of coded transactions. The system prepares drafts; it does not post them on its own unless you approve a rule for a specific, low-risk type.']},
   {h:'Where to start',table:[['If your main problem is…','Start with','What we measure'],['Clients send records late','Document chasing','Documents received before the deadline week'],['Staff retype invoices','Invoice reading and coding','Hours of data entry per accountant'],['The phone rings all through January','Status answers','Calls handled without an accountant'],['New clients take weeks to set up','Onboarding sequence','Days from signed letter to first records']]},
   {h:'What it costs',p:['A pilot on one workflow is '+pilot+' ('+pilotP+' with the launch offer) and takes 2–4 weeks, including tests on last season’s real documents. Connecting several workflows with agents that read, check and draft across systems starts at '+custom+' ('+customP+'). Ongoing care is '+care+' a month ('+careP+'), and AI usage is billed by the providers at cost on your own accounts.','A quick check: take the hours your team spends on chasing and data entry in a filing month, multiply by their hourly cost, and compare with the pilot price. The calculator on our pricing page does this for you.']},
   {h:'Data protection',p:['Client records are personal data under UK GDPR. We keep them in your accounts and your accounting software, limit access to what each workflow needs, keep a log of every action and sign a data processing agreement before launch. Your data is not used to train public models.']},
  ],
  faq:[['Which accounting software do you connect to?','Xero, QuickBooks and Sage, plus practice management tools through their APIs. Spreadsheets and email work too.'],['Can AI file returns or submit MTD updates?','No. It prepares the records and reminders. An accountant reviews and submits.'],['How accurate is the coding?','We measure it in the pilot on your own past documents and agree an acceptable accuracy before go-live. Anything below the confidence threshold goes to a person.'],['How much of our time does the pilot need?','A few hours from the person who runs the workflow today: to show us the process and to check results in the test week.']],
  links:[['industries/accounting','AI for accounting firms'],['services/ai-automation','AI automation'],['blog/ai-implementation-cost','How much does AI implementation cost?']]},
 {slug:'ai-for-recruitment-agencies',cat:'Recruitment',date:'2026-10-08',dateLabel:'8 October 2026',minutes:7,
  title:'AI for recruitment agencies: screening and scheduling',
  description:'How a recruitment agency can use AI to screen CVs, book interviews and keep candidates informed, where people must stay in charge and what it costs.',
  excerpt:'Screening, scheduling and candidate follow-up: what to automate, where a consultant must decide and what a pilot costs.',
  answer:'A recruitment agency can use AI to score CVs against the brief with written reasons, reply to every applicant the same day, book first calls and interviews, and keep candidates and clients updated. Consultants make every shortlist and hiring decision. A pilot on one stage of your process takes 2–4 weeks and costs '+pilot+' ('+pilotP+' with the launch offer). Prices exclude VAT.',
  blocks:[
   {h:'Where the hours go',p:['In most agencies the time does not go on finding candidates. It goes on reading applications that do not fit, chasing people to agree a time, and answering “any news?” messages. These are the parts AI handles well, because they follow rules you can write down.']},
   {h:'Screening: scores with reasons, decisions by people',list:['Each CV is compared with the brief: must-have skills, right to work, location, notice period and salary range.','The result is a score with a short written reason for every point, so a consultant can check it in seconds.','Candidates who miss a must-have are not rejected automatically. They go to a “check” list for a consultant to review.','The consultant builds the shortlist. The system never sends a candidate to a client on its own.']},
   {h:'Scheduling without the back-and-forth',p:['Once a consultant approves a candidate, the system offers interview slots from the consultant’s and the client’s calendars in Outlook or Google. The candidate picks a time by email, SMS or WhatsApp. Reminders go out the day before and an hour before, and a cancellation offers the next free slot.']},
   {h:'Follow-up that keeps candidates warm',list:['Every applicant gets a reply the same day, with the next step and a date.','Candidates can ask about their application at any hour and get the current status from your CRM, such as Bullhorn.','After each interview, the client is asked for feedback with a short form, and the candidate hears back once a consultant approves the message.','Placed candidates get check-ins at the points you choose, which also tells you early when a placement is at risk.']},
   {h:'The rules you need to follow',p:['UK GDPR restricts decisions based solely on automated processing that have a significant effect on a person, and a decision not to put someone forward can be one. The Equality Act 2010 applies to how candidates are screened, whoever or whatever does it. That is why we design screening as a recommendation with reasons, keep a person on every decision, check on your past roles that scores do not depend on things unrelated to the job, such as name, age or address and tell candidates how their data is used. The ICO has published recommendations for AI tools in recruitment, and we follow them in the design.']},
   {h:'What it costs',table:[['Format','What you get','Price (launch offer)'],['Pilot','One stage automated: screening, scheduling or follow-up','2–4 weeks, '+pilotP],['Custom solution','Several stages connected, agents across your CRM, email and calendars','from '+customP],['Ongoing care','Rule updates for new roles, monitoring and fixes',careP+'/mo']],p:['AI usage is billed by the providers at cost on your own accounts. A sensible first pilot is the stage where your consultants lose the most hours each week.']},
  ],
  faq:[['Will candidates know they are talking to AI?','Yes. Messages say they come from an assistant, and a candidate can ask for a person at any time.'],['Does it work with Bullhorn?','Yes, through its API. We also connect to other recruitment CRMs, Outlook, Google Calendar and job boards.'],['Can it reject candidates?','Not on its own. It recommends, with reasons. A consultant decides and approves the message.'],['How do you check for bias?','Before launch we run the scoring on your past roles and check that it follows the brief and nothing else. We review a sample every month.']],
  links:[['industries/recruitment','AI for recruitment agencies'],['services/ai-agents','AI agents'],['blog/ai-for-accounting-firms','AI for accounting firms: what to automate first']]},
];
