// praxenai.com: UK wording for shared English copy written for praxenai.ge.
// Key: the English string as written in the components; value: what the international site shows.
// Used by copyFn only when NEXT_PUBLIC_MARKET=intl, so praxenai.ge is unaffected.
export const intlText:Record<string,string>={
 "Telegram · applicant":"WhatsApp · applicant",
 "1C:Accounting":"Xero",
 "1C:Trade Management":"Shopify",
 "1C:Document Flow":"SharePoint",
 "1C:TMS Logistics":"TMS",
 "AI writes unique product descriptions in your brand voice in three languages. An editor reviews a sample and publishes.":"AI writes unique product descriptions in your brand voice. An editor reviews a sample and publishes.",
 "Enter your numbers to see the hours and lari AI could free up, the revenue from leads you lose today and how fast it pays back.":"Enter your numbers to see the hours and pounds AI could free up, the revenue from leads you lose today and how fast it pays back.",
 " ₾ a month; ":" a month; ",
 " ₾ each. I would like to discuss an audit.":" each. I would like to discuss an audit.",
 "Hours and lari AI could free in each process and what to start with.":"Hours and pounds AI could free in each process and what to start with.",
 "WhatsApp assistant · 2–4 weeks · 3,200 ₾":"AI receptionist · 2 weeks · from £950",
 "1C and CRM integrators":"CRM and IT consultancies",
 "Add AI to your amoCRM, Bitrix24 and 1C projects.":"Add AI to your HubSpot, Salesforce and Microsoft 365 projects.",
 "Demos, case studies and decks in three languages for your sales.":"Demos, case studies and decks for your sales team.",
 "A partner programme for anyone who already serves companies in Georgia: you bring the client, we implement AI, you earn a reward.":"A partner programme for agencies, accountants and IT firms that already serve small businesses: you bring the client, we implement AI, you earn a reward.",
 "replies to customers on WhatsApp, Instagram and Telegram":"calls, chat and WhatsApp answered",
 "Batumi":"London",
 "Four-hotel network, Adjara":"Four-hotel group, UK",
 "Conversations in GE / EN / RU":"Conversations in English and 30+ languages",
 "Need 30 chairs in Batumi":"Need 30 chairs in Manchester",
 "Law of Georgia on Personal Data Protection":"UK GDPR and the Data Protection Act 2018",
 "The data controller is Praxen AI (Georgia). For any data question, message us on Telegram or call: ":"The data controller is Praxen AI, an AI implementation company based in Georgia. For any data question, email hello@praxenai.ge or call: ",
 "We comply with the Law of Georgia on Personal Data Protection.":"We process personal data in line with UK GDPR and the Data Protection Act 2018.",
 "From the enquiry form: your contact (WhatsApp, Telegram or phone), the options you chose, your message, the page you sent it from and the traffic source (such as UTM tags).":"From the enquiry form: your contact (email, WhatsApp or phone), the options you chose, your message, the page you sent it from and the traffic source (such as UTM tags).",
 "Enquiries reach us via Telegram, email and the amoCRM system. Call bookings (name, email, chosen time) are handled by Cal.com. The site runs on a hosting provider.":"Enquiries reach us by email and Telegram and may be stored in our CRM. Call bookings (name, email, chosen time) are handled by Cal.com. The site runs on Cloudflare. Where data leaves the UK, we rely on UK GDPR safeguards such as the International Data Transfer Agreement.",
 "You may ask what data we hold, correct or delete it, withdraw consent and complain to the Personal Data Protection Service of Georgia. Contact us and we will reply within 10 working days.":"You may ask what data we hold, correct or delete it, object to or restrict its use, withdraw consent and complain to the Information Commissioner’s Office (ico.org.uk). Contact us and we will reply within one month.",
 "AI assistant on WhatsApp, Telegram and your website":"AI assistant on your phone line, website and WhatsApp",
 "Replies in seconds in three languages and hands managers ready leads.":"Replies in seconds, day and night, and hands your team ready leads.",
 "Sorts enquiries, fills in amoCRM or Bitrix24 and reminds managers of tasks.":"Sorts enquiries, fills in HubSpot or Pipedrive and reminds your team of tasks.",
 "Questions go straight to Telegram or WhatsApp, no middlemen.":"Questions go straight to email or WhatsApp, no middlemen.",
 "Team training from 1,900 ₾ ($700), tool implementation for your process from 3,200 ₾ ($1,200), custom development from 6,700 ₾ ($2,500), ongoing maintenance from 550 ₾ ($200) a month. The solution runs on your accounts: AI tokens and servers are paid directly to the providers. The audit is free, and we fix the pilot price before work begins.":"Team training from £850, an implementation pilot from £2,900, custom development from £6,500 and ongoing care from £350 a month; an AI receptionist from £950 setup plus £249 a month. Our launch offer takes 30% off for the first UK clients. The solution runs on your accounts: AI usage and call minutes are paid directly to the providers. The first call is free, and we fix the pilot price before work begins.",
 "Praxen AI is an AI implementation company in Georgia. We build AI assistants and chatbots for WhatsApp, Telegram and websites, deploy AI agents that update your CRM and process documents, and train teams to use AI. Based in Batumi, we work with companies in Tbilisi and across Georgia, on site and remotely, in Georgian, English and Russian. Every project starts with a free audit. Team training starts at 1,900 ₾, implementation for your process at 3,200 ₾, and a pilot on one workflow takes from 2 weeks.":"Praxen AI sets up AI receptionists, chatbots and AI automation for small and mid-sized businesses. We build voice agents that answer calls and book appointments, assistants for websites and WhatsApp, and AI agents that update your CRM and process documents, and we train teams to use AI safely. Our team is based in Georgia (three to four hours ahead of the UK) and works remotely with clients in the UK and Europe during UK business hours. Every project starts with a free call; a pilot on one workflow takes 2–4 weeks at a fixed price.",
 "We design solutions for Georgian, English and Russian and evaluate answers on your use cases. Team training is available in Russian and English; Georgian delivery is agreed separately.":"We build and test solutions in English, and assistants can also answer in 30+ other languages your customers speak. Team training is delivered in English.",
 "The solution runs on your accounts and servers: you pay AI tokens and infrastructure directly to the providers. We hand over access, code and instructions and train the owners. Ongoing maintenance is available from 550 ₾ a month: we update the knowledge base, review answers, fix errors and improve workflows.":"The solution runs on your accounts: you pay AI usage and call minutes directly to the providers. We hand over access, configuration and instructions and train the owners. Ongoing care is available from £350 a month (30% off with the launch offer): we update the knowledge base, review answers, fix errors and improve workflows.",
 "Implementing ready tools starts at 3,200 ₾ ($1,200): a pilot on one workflow in 2–4 weeks on your real data. Custom development for your systems starts at 6,700 ₾ ($2,500), ongoing maintenance from 550 ₾ a month. The audit is free and the pilot price is fixed before work begins.":"An implementation pilot starts at £2,900: one workflow in 2–4 weeks on your real data. Custom development for your systems starts at £6,500, ongoing care from £350 a month, and the launch offer takes 30% off. The first call is free and the pilot price is fixed before work begins.",
 "1C / CRM integrator":"CRM / IT consultancy",
 "Practical AI for business in Georgia":"Practical AI for small and mid-sized businesses",
 "AI answers customers on WhatsApp and Telegram, fills in your CRM and drafts documents in three languages.":"AI answers your calls and chats, books appointments, fills in your CRM and drafts documents — around the clock.",
 "Hi, we need 30 chairs in Batumi tomorrow. Can you send prices?":"Hi, we need 30 chairs in Manchester tomorrow. Can you send prices?",
 "Three illustrative scenarios for businesses in Georgia. Explore the workflow and evaluation criteria.":"Three illustrative scenarios for small businesses. Explore the workflow and evaluation criteria.",
 "Message on Telegram":"Email us",
 "Georgia · EN / GE / RU":"Remote · UK business hours",
 "Check your contact: include the country code or a valid Telegram username.":"Check your contact: a valid email, or a phone number with the country code.",
 "AI implementation for businesses in Georgia: chatbots and AI assistants for WhatsApp and Telegram, CRM and document automation, team training.":"AI receptionists, chatbots and AI automation for small and mid-sized businesses in the UK and Europe.",
 "For departments":"Services",
 "Solutions":"Pricing",
};
