import type {Copy} from './content';
// Most requested AI jobs per department; i is the icon name.
export type Job={i:string;t:Copy;d:Copy};
export const jobs:Record<string,Job[]>={
"sales":[
 {"i":"message-circle","t":["Квалификация лидов 24/7","24/7 lead qualification","ლიდების კვალიფიკაცია 24/7"],"d":["Бот в WhatsApp, Telegram и на сайте уточняет задачу, бюджет и сроки и передаёт в CRM только тёплых клиентов.","A bot in WhatsApp, Telegram and on your site clarifies need, budget and timing, and passes only warm leads to the CRM.","ბოტი WhatsApp‑ში, Telegram‑სა და საიტზე აზუსტებს საჭიროებას, ბიუჯეტსა და ვადებს და CRM‑ში მხოლოდ თბილ ლიდებს გადასცემს."]},
 {"i":"phone-call","t":["Голосовой агент: входящие и исходящие","Voice agent: inbound and outbound","ხმოვანი აგენტი: შემომავალი და გამავალი"],"d":["Принимает звонки, обзванивает базу, напоминает о встречах и реактивирует «спящих» клиентов. Сложные разговоры переводит на менеджера.","Answers calls, dials your list, confirms meetings and re-engages dormant clients. Hands complex calls to a manager.","პასუხობს ზარებს, რეკავს ბაზაში, ახსენებს შეხვედრებს და აბრუნებს „მძინარე“ კლიენტებს. რთულ საუბარს მენეჯერს გადასცემს."]},
 {"i":"file-text","t":["КП и счета за минуты","Proposals and invoices in minutes","შეთავაზებები და ინვოისები წუთებში"],"d":["Собирает предложение по актуальному прайсу и остаткам, применяет только ваши скидки. Менеджер проверяет и отправляет.","Builds a proposal from current prices and stock, applying only your discounts. A manager reviews and sends.","ადგენს შეთავაზებას მიმდინარე ფასებითა და მარაგით, მხოლოდ თქვენი ფასდაკლებებით. მენეჯერი ამოწმებს და აგზავნის."]},
 {"i":"audio-lines","t":["Анализ звонков и автозаполнение CRM","Call analysis and CRM auto-fill","ზარების ანალიზი და CRM‑ის ავტოშევსება"],"d":["Расшифровывает разговоры, заполняет поля сделки, ставит задачи и оценивает работу по скрипту.","Transcribes calls, fills deal fields, creates follow-ups and scores script compliance.","შიფრავს საუბრებს, ავსებს გარიგების ველებს, ქმნის ამოცანებს და აფასებს სკრიპტის შესრულებას."]},
],
"marketing":[
 {"i":"pen-tool","t":["Контент в голосе бренда","On-brand content engine","კონტენტი ბრენდის ხმით"],"d":["Посты, рассылки и тексты для лендингов по вашему брендбуку. Редактор утверждает перед публикацией.","Posts, emails and landing copy that follow your brand book. An editor approves before publishing.","პოსტები, წერილები და ტექსტები თქვენი ბრენდბუქით. რედაქტორი ამტკიცებს გამოქვეყნებამდე."]},
 {"i":"search","t":["SEO-статьи и описания товаров","SEO articles and product copy","SEO სტატიები და პროდუქტის აღწერები"],"d":["Семантика, структура и уникальные описания для каталога на трёх языках.","Keywords, structure and unique catalogue descriptions in three languages.","სემანტიკა, სტრუქტურა და უნიკალური აღწერები სამ ენაზე."]},
 {"i":"line-chart","t":["Отчёты по кампаниям","Campaign reporting","კამპანიების ანგარიშები"],"d":["Собирает данные из рекламных кабинетов и аналитики и присылает короткую сводку: что выросло, что просело и почему.","Pulls ad and analytics data and sends a short summary: what grew, what dropped and why.","აგროვებს მონაცემებს და აგზავნის მოკლე შეჯამებას: რა გაიზარდა, რა შემცირდა და რატომ."]},
 {"i":"star","t":["Отзывы и репутация","Reviews and reputation","შეფასებები და რეპუტაცია"],"d":["Отслеживает отзывы на картах и площадках, готовит ответы и сразу передаёт негатив ответственному.","Monitors reviews on maps and marketplaces, drafts replies and escalates negative feedback at once.","აკვირდება შეფასებებს რუკებსა და პლატფორმებზე, ამზადებს პასუხებს და ნეგატივს მაშინვე გადასცემს."]},
],
"support":[
 {"i":"book-open","t":["Первая линия по базе знаний","First line from your knowledge base","პირველი ხაზი ცოდნის ბაზით"],"d":["Отвечает 24/7 в чатах и почте на трёх языках, ссылается на источник. Если ответа нет — переводит на оператора.","Answers 24/7 in chat and email in three languages, citing the source. No answer — it hands over to an agent.","პასუხობს 24/7 ჩატსა და ფოსტაში სამ ენაზე, წყაროს მითითებით. პასუხი თუ არ არის — ოპერატორს გადასცემს."]},
 {"i":"phone-incoming","t":["Голосовой ассистент колл-центра","Voice assistant for your call centre","ქოლ‑ცენტრის ხმოვანი ასისტენტი"],"d":["Снимает типовые звонки: статус заказа, запись, перенос. Остальные — оператору с кратким резюме.","Handles routine calls — order status, bookings, rescheduling — and passes the rest to an agent with a summary.","ამუშავებს ტიპურ ზარებს — შეკვეთის სტატუსი, ჩაწერა, გადატანა — დანარჩენს ოპერატორს გადასცემს."]},
 {"i":"pen-line","t":["Копилот оператора","Agent copilot","ოპერატორის ასისტენტი"],"d":["Саммари длинной переписки и черновик ответа прямо в helpdesk. Оператор правит и отправляет.","A thread summary and a draft reply right in the helpdesk. The agent edits and sends.","მიმოწერის შეჯამება და პასუხის მონახაზი პირდაპირ helpdesk‑ში."]},
 {"i":"shield-check","t":["Контроль качества 100% диалогов","QA on 100% of conversations","ხარისხის კონტროლი 100% დიალოგზე"],"d":["Оценивает каждый чат и звонок по вашим критериям и показывает, где теряются клиенты.","Scores every chat and call against your criteria and shows where customers are lost.","აფასებს ყველა ჩატსა და ზარს თქვენი კრიტერიუმებით და აჩვენებს, სად იკარგებიან კლიენტები."]},
],
"operations":[
 {"i":"scan-line","t":["Документы → учётная система","Documents → your system","დოკუმენტები → სისტემაში"],"d":["Счета, накладные и анкеты, даже плохие сканы, превращаются в заполненные поля. Спорные значения подтверждает человек.","Invoices, delivery notes and forms — even poor scans — become filled fields. A person confirms uncertain values.","ინვოისები, ზედნადებები და ანკეტები ველებად იქცევა. საეჭვო მნიშვნელობებს ადამიანი ადასტურებს."]},
 {"i":"inbox","t":["Разбор общей почты","Shared inbox triage","საერთო ფოსტის დახარისხება"],"d":["Каждое письмо получает тему, приоритет и ответственного. Ничего не теряется в общем ящике.","Every email gets a topic, priority and owner. Nothing gets lost in the shared inbox.","ყველა წერილი იღებს თემას, პრიორიტეტსა და პასუხისმგებელს."]},
 {"i":"library","t":["Ассистент по регламентам","Policy assistant","რეგლამენტების ასისტენტი"],"d":["Сотрудники находят нужную инструкцию или шаблон за секунды — в мессенджере, со ссылкой на документ.","Staff find the right procedure or template in seconds — in a messenger, with a link to the document.","თანამშრომლები წამებში პოულობენ ინსტრუქციას ან შაბლონს — მესენჯერში, დოკუმენტის ბმულით."]},
 {"i":"file-bar-chart","t":["Регулярная отчётность","Recurring reports","რეგულარული ანგარიშგება"],"d":["Еженедельные отчёты собираются из таблиц и систем автоматически и приходят ответственным.","Weekly reports are compiled from sheets and systems automatically and sent to owners.","ყოველკვირეული ანგარიშები ავტომატურად გროვდება და პასუხისმგებლებს მიდის."]},
],
"hr":[
 {"i":"user-search","t":["Скрининг резюме и первичное интервью","CV screening and first interview","რეზიუმეს სკრინინგი და პირველი ინტერვიუ"],"d":["Отбирает кандидатов по вашим критериям и проводит первое интервью в чате. Решение о найме — за HR.","Shortlists candidates by your criteria and runs a first chat interview. Hiring decisions stay with HR.","არჩევს კანდიდატებს თქვენი კრიტერიუმებით და ატარებს პირველ ინტერვიუს. გადაწყვეტილება HR‑ს რჩება."]},
 {"i":"message-square-text","t":["HR-бот по внутренним вопросам","HR helpdesk bot","HR ბოტი შიდა კითხვებზე"],"d":["Отпуск, больничный, справки и шаблоны — ответы по вашим правилам в Slack или Telegram.","Leave, sick days, certificates and templates — answers based on your rules in Slack or Telegram.","შვებულება, ბიულეტენი, ცნობები — პასუხები თქვენი წესებით Slack‑ში ან Telegram‑ში."]},
 {"i":"route","t":["Онбординг по ролям","Role-based onboarding","ონბორდინგი როლების მიხედვით"],"d":["Ведёт новичка по плану первых недель, выдаёт материалы и проверяет, что они усвоены.","Guides new hires through their first weeks, delivers materials and checks understanding.","ახალ თანამშრომელს ატარებს პირველი კვირების გეგმით და ამოწმებს ცოდნას."]},
 {"i":"graduation-cap","t":["Обучение и тренажёры","Training and practice","სწავლება და ტრენაჟორები"],"d":["Курсы, тесты и ролевые тренировки на основе ваших инструкций и записей лучших сотрудников.","Courses, quizzes and role-play built from your manuals and top performers.","კურსები, ტესტები და როლური ვარჯიშები თქვენი ინსტრუქციების საფუძველზე."]},
],
"finance":[
 {"i":"receipt","t":["Первичка без ручного ввода","Source documents without manual entry","პირველადი დოკუმენტები ხელით შეყვანის გარეშე"],"d":["Счета, акты и накладные превращаются в черновики проводок в 1С или ERP. Проводит бухгалтер.","Invoices, statements and delivery notes become draft entries in 1C or your ERP. An accountant posts them.","ინვოისები და აქტები 1C‑ში ან ERP‑ში მონახაზებად იქცევა. ატარებს ბუღალტერი."]},
 {"i":"scale","t":["Сверка взаиморасчётов","Reconciliation","ურთიერთანგარიშსწორების შედარება"],"d":["Сопоставляет акты сверки с контрагентами и подсвечивает расхождения с черновиком письма.","Matches counterparty statements and flags discrepancies with a draft email.","ადარებს კონტრაგენტების აქტებს და აჩვენებს შეუსაბამობებს."]},
 {"i":"camera","t":["Авансовые отчёты по фото чека","Expenses from receipt photos","ავანსის ანგარიში ქვითრის ფოტოთი"],"d":["Сотрудник отправляет фото в бот — бухгалтерия получает готовую строку отчёта.","Staff send a photo to a bot — accounting gets a ready expense line.","თანამშრომელი ფოტოს აგზავნის ბოტში — ბუღალტერია იღებს მზა ხაზს."]},
 {"i":"bell-ring","t":["Контроль дебиторки","Receivables follow-up","დებიტორული დავალიანების კონტროლი"],"d":["Вежливые напоминания об оплате в мессенджере или звонком и ежедневная сводка просрочек.","Polite payment reminders by message or call and a daily overdue summary.","გადახდის თავაზიანი შეხსენებები და ვადაგადაცილების ყოველდღიური შეჯამება."]},
],
"procurement":[
 {"i":"table-2","t":["Сравнение КП поставщиков","Supplier quote comparison","მომწოდებლების შეთავაზებების შედარება"],"d":["PDF, Excel и письма сводятся в одну таблицу: цена, срок, условия — в единых единицах.","PDFs, spreadsheets and emails become one table — price, lead time, terms — in common units.","PDF, Excel და წერილები ერთ ცხრილში: ფასი, ვადა, პირობები."]},
 {"i":"send","t":["Рассылка запросов (RFQ)","RFQ outreach","მოთხოვნების დაგზავნა (RFQ)"],"d":["Готовит и отправляет запросы поставщикам, собирает ответы и напоминает тем, кто молчит.","Prepares and sends requests to suppliers, collects replies and chases non-responders.","ამზადებს და აგზავნის მოთხოვნებს, აგროვებს პასუხებს და ახსენებს."]},
 {"i":"file-check-2","t":["Сверка инвойсов и договоров","Invoice and contract checks","ინვოისებისა და ხელშეკრულებების შემოწმება"],"d":["Сравнивает счёт с заказом и договором и отмечает отличия в цене, количестве и условиях.","Compares invoices with POs and contracts and flags price, quantity and term differences.","ადარებს ინვოისს შეკვეთასა და ხელშეკრულებას და აჩვენებს განსხვავებებს."]},
 {"i":"truck","t":["Контроль поставок","Delivery tracking","მიწოდების კონტროლი"],"d":["Статусы из писем перевозчиков и трек-номеров обновляются в системе, задержки видны сразу.","Statuses from carrier emails and tracking numbers update your system; delays show up at once.","სტატუსები ავტომატურად ახლდება, დაგვიანება მაშინვე ჩანს."]},
],
"leadership":[
 {"i":"radar","t":["AI-аудит и расчёт окупаемости","AI audit and ROI model","AI აუდიტი და ანაზღაურების გათვლა"],"d":["Находим процессы с понятной экономикой и считаем эффект пилота до начала разработки.","We find processes with clear economics and model pilot impact before development.","ვპოულობთ პროცესებს მკაფიო ეკონომიკით და ვითვლით პილოტის ეფექტს."]},
 {"i":"bar-chart-3","t":["Сводки по запросу","Answers from your data","შეჯამებები მოთხოვნით"],"d":["Спросите в Telegram «как прошла неделя» — ассистент ответит по данным CRM и учёта.","Ask in Telegram “how was the week” — the assistant answers from CRM and accounting data.","ჰკითხეთ Telegram‑ში „როგორ წავიდა კვირა“ — ასისტენტი CRM‑ის მონაცემებით გიპასუხებთ."]},
 {"i":"notebook-pen","t":["Ассистент руководителя","Executive assistant","ხელმძღვანელის ასისტენტი"],"d":["Протоколы встреч, задачи по ответственным и контроль сроков без ручной переписки.","Meeting notes, owner tasks and deadline tracking without manual follow-ups.","შეხვედრის ოქმები, ამოცანები და ვადების კონტროლი."]},
 {"i":"users","t":["Стратегическая сессия для команды","Leadership workshop","სტრატეგიული სესია გუნდისთვის"],"d":["За один день выбираем приоритетные процессы, роли и план внедрения на квартал.","In one day we pick priority processes, owners and a quarterly rollout plan.","ერთ დღეში ვირჩევთ პრიორიტეტულ პროცესებს და კვარტლის გეგმას."]},
],
};
