import {base} from './base';
// Service logos: a bundled brand SVG (Simple Icons, CC0) when one exists, otherwise the vendor's
// favicon; if neither loads, a coloured tile with the vendor's initials. Names do not imply partnerships.
const local:Record<string,string>={Claude:'claude',HubSpot:'hubspot',Zendesk:'zendesk',Intercom:'intercom',Notion:'notion',Telegram:'telegram',WhatsApp:'whatsapp',SAP:'sap',Meta:'meta','Google Analytics':'googleanalytics',WordPress:'wordpress',Mailchimp:'mailchimp',Figma:'figma',Moodle:'moodle',Shopify:'shopify',WooCommerce:'woocommerce',Instagram:'instagram','Booking.com':'bookingdotcom','Google Sheets':'googlesheets',Jira:'jira',Asana:'asana',Gmail:'gmail',Buffer:'buffer'};
const domains:Record<string,string>={OpenAI:'openai.com',Claude:'claude.ai',Midjourney:'midjourney.com',amoCRM:'amocrm.ru',Bitrix24:'bitrix24.ru',HubSpot:'hubspot.com',Salesforce:'salesforce.com',Zendesk:'zendesk.com',Intercom:'intercom.com',Slack:'slack.com',Notion:'notion.so',Telegram:'telegram.org',WhatsApp:'whatsapp.com','Google Workspace':'workspace.google.com','1C':'1c.ru','1C:Medicine':'1c.ru','1C-Bitrix':'1c-bitrix.ru',SAP:'sap.com',Oracle:'oracle.com','Opera PMS':'oracle.com','Microsoft Dynamics':'dynamics.microsoft.com','Microsoft Teams':'teams.microsoft.com',Meta:'meta.com','Google Analytics':'analytics.google.com',WordPress:'wordpress.org',Mailchimp:'mailchimp.com',Figma:'figma.com',Moodle:'moodle.org',iSpring:'ispringsolutions.com',BambooHR:'bamboohr.com',Shopify:'shopify.com',WooCommerce:'woocommerce.com',RetailCRM:'retailcrm.ru',Instagram:'instagram.com',MoySklad:'moysklad.ru',Cloudbeds:'cloudbeds.com',Bnovo:'bnovo.ru',TravelLine:'travelline.ru','Booking.com':'booking.com','Google Sheets':'sheets.google.com',Profitbase:'profitbase.ru',iiko:'iiko.ru',r_keeper:'rkeeper.ru',Poster:'joinposter.com',YCLIENTS:'yclients.com',GetCourse:'getcourse.ru',AlfaCRM:'alfacrm.pro',Jira:'atlassian.com',Asana:'asana.com',LinkedIn:'linkedin.com',Gmail:'mail.google.com',Buffer:'buffer.com',Jivo:'jivo.ru'};
const colors:Record<string,string>={amoCRM:'#1a8ae5','1C':'#ffd400','1C-Bitrix':'#2fc6f6','1C:Medicine':'#ffd400',Bitrix24:'#2fc6f6',Midjourney:'#000000',Salesforce:'#00a1e0','Microsoft Dynamics':'#0b53ce','Microsoft Teams':'#5059c9',Excel:'#217346',PDF:'#e5252a',Jivo:'#00b05a',iSpring:'#e94f35',BambooHR:'#73c41d',Oracle:'#f80000',RetailCRM:'#0068ff',MoySklad:'#0066b3','Opera PMS':'#c74634',Cloudbeds:'#2b6cf6',Bnovo:'#ff5a1f',TravelLine:'#f26522',Profitbase:'#2e7cf6',MacroCRM:'#1c64f2',iiko:'#6cbe45',r_keeper:'#d7262d',Poster:'#f6a700',Medesk:'#1fa2e6',YCLIENTS:'#6a4cf0',GetCourse:'#2b90d9',AlfaCRM:'#ff6f00',LinkedIn:'#0a66c2','Google Workspace':'#4285f4',OpenAI:'#111111',Claude:'#d97757',SAP:'#0faaff',HubSpot:'#ff7a59',Zendesk:'#03363d',Intercom:'#1f8ded',Slack:'#4a154b',Notion:'#000000',Telegram:'#26a5e4',WhatsApp:'#25d366',Meta:'#0467df','Google Analytics':'#e37400',WordPress:'#21759b',Mailchimp:'#241c15',Figma:'#f24e1e',Moodle:'#f98012',Shopify:'#7ab55c',WooCommerce:'#96588a',Instagram:'#e4405f','Booking.com':'#003580','Google Sheets':'#34a853',Jira:'#0052cc',Asana:'#f06a6a',Gmail:'#ea4335',Buffer:'#231f20'};
const initials:Record<string,string>={amoCRM:'amo',PDF:'PDF',Excel:'X',r_keeper:'rk','1C':'1С','1C-Bitrix':'1С','1C:Medicine':'1С',iiko:'ii',MoySklad:'МС','Microsoft Dynamics':'D','Microsoft Teams':'T','Opera PMS':'O'};

export type LogoInfo={name:string;srcs:string[];mono:string;monoFg:string;ini:string};
export const logo=(name:string):LogoInfo=>{
 const domain=domains[name],mono=colors[name]||'#5d6779';
 return {name,srcs:[...(local[name]?[base+'/logos/'+local[name]+'.svg']:[]),...(domain?['https://www.google.com/s2/favicons?sz=64&domain='+domain]:[])],mono,monoFg:mono==='#ffd400'?'#d4001a':'#ffffff',ini:initials[name]||name.replace(/[^A-Za-zА-Яа-я0-9]/g,'').slice(0,2)};
};

export const marqueeLogos=['OpenAI','Claude','Midjourney','amoCRM','Bitrix24','HubSpot','Salesforce','Zendesk','Intercom','Slack','Notion','Telegram','WhatsApp','Google Workspace','1C','SAP'];

// Systems shown in "Sources and integrations" on each department and industry page.
export const pageLogos:Record<string,string[]>={sales:['amoCRM','Bitrix24','HubSpot','Salesforce','Telegram','WhatsApp'],support:['Zendesk','Intercom','Notion','WhatsApp','Telegram','Jivo'],hr:['Slack','Microsoft Teams','Moodle','iSpring','BambooHR','Telegram'],marketing:['Meta','Google Analytics','WordPress','Mailchimp','Figma','Telegram'],procurement:['SAP','Oracle','Microsoft Dynamics','1C','Excel','PDF'],finance:['1C','SAP','Excel','Google Sheets','PDF'],operations:['Google Workspace','Notion','Slack','1C','Excel','PDF'],leadership:['Bitrix24','amoCRM','Google Sheets','Telegram','Slack'],retail:['Shopify','WooCommerce','1C-Bitrix','RetailCRM','Instagram','WhatsApp'],wholesale:['1C','MoySklad','SAP','Bitrix24','Excel','WhatsApp'],hotels:['Opera PMS','Cloudbeds','Bnovo','TravelLine','Booking.com','WhatsApp'],tourism:['Google Sheets','Booking.com','WhatsApp','Telegram','PDF'],'real-estate':['amoCRM','Bitrix24','WhatsApp','Telegram','Instagram'],developers:['amoCRM','Bitrix24','Profitbase','MacroCRM','WhatsApp'],restaurants:['iiko','r_keeper','Poster','Instagram','WhatsApp'],clinics:['Medesk','YCLIENTS','1C:Medicine','WhatsApp','Telegram'],logistics:['1C','SAP','Excel','Telegram','WhatsApp','PDF'],manufacturing:['SAP','1C','Excel','PDF','Microsoft Teams'],services:['Notion','Jira','Asana','Slack','Google Workspace','Bitrix24'],education:['GetCourse','Moodle','iSpring','amoCRM','AlfaCRM','Telegram']};
