import {Lang,t} from './content';
import {casesVerified} from './proof';

export type C=(ru:string,en:string,ka:string)=>string;
export const copyFn=(lang:Lang):C=>(ru,en,ka)=>t([ru,en,ka],lang);

export const sections=['industries','departments','training','solutions','cases'] as const;
export const sectionLabel=(c:C,n:string)=>({industries:c('Отрасли','Industries','ინდუსტრიები'),departments:c('Для отделов','For departments','განყოფილებებისთვის'),training:c('Обучение','Training','სწავლება'),solutions:c('Решения','Solutions','გადაწყვეტილებები'),cases:c('Примеры решений','Solution examples','გადაწყვეტილებების მაგალითები')} as Record<string,string>)[n]||n;

// Department pages get their own call to action; everything else uses the free audit.
export const actionFor=(c:C,slug?:string)=>{
 const map:Record<string,string>={sales:c('Аудит отдела продаж','Audit my sales process','გაყიდვების აუდიტი'),support:c('Аудит поддержки','Audit my helpdesk','მხარდაჭერის აუდიტი'),hr:c('Аудит онбординга','Audit our onboarding','ონბორდინგის აუდიტი'),marketing:c('Аудит маркетинга','Audit our marketing','მარკეტინგის აუდიტი'),procurement:c('Автоматизировать сравнение КП','Automate quote comparison','შეთავაზებების შედარების ავტომატიზაცია'),finance:c('Аудит учёта','Audit our accounting','აღრიცხვის აუდიტი'),operations:c('Аудит бэк-офиса','Audit our back office','ბექ‑ოფისის აუდიტი'),leadership:c('Стратегический аудит','Book a strategy audit','სტრატეგიული აუდიტი')};
 return (slug&&map[slug])||c('Бесплатный аудит процесса','Get a free AI audit','უფასო AI აუდიტი');
};

export function siteCopy(c:C,slug?:string){
 return {
  action:actionFor(c,slug),
  skip:c('К содержанию','Skip to content','შინაარსზე გადასვლა'),
  mainNav:c('Основная навигация','Main navigation','მთავარი ნავიგაცია'),
  langLabel:c('Язык сайта','Website language','საიტის ენა'),
  actionHeader:c('Бесплатный аудит','Free AI audit','უფასო აუდიტი'),
  viewAll:c('Смотреть всё','View all','ყველას ნახვა'),
  openMenu:c('Открыть меню','Open menu','მენიუს გახსნა'),closeMenu:c('Закрыть меню','Close menu','მენიუს დახურვა'),
  heroEyebrow:c('Практический ИИ для бизнеса в Грузии','Practical AI for business in Georgia','პრაქტიკული AI ბიზნესისთვის საქართველოში'),
  heroH1a:c('Внедряем ИИ','We bring AI','ვნერგავთ AI‑ს'),heroH1b:c('в бизнес-процессы.','into your workflows.','ბიზნესპროცესებში.'),heroH1c:c('Рутины — в 2⁠–⁠3 раза меньше.','2⁠–⁠3× less routine work.','2⁠–⁠3‑ჯერ ნაკლები რუტინა.'),
  heroIntro:c('Чат-боты отвечают клиентам в WhatsApp и Telegram, ИИ-агенты заполняют CRM и готовят документы — на грузинском, английском и русском. Решения принимает ваша команда.','AI chatbots answer customers on WhatsApp and Telegram, AI agents fill in your CRM and draft documents — in Georgian, English and Russian. Your team makes the decisions.','AI ჩატბოტები პასუხობენ კლიენტებს WhatsApp‑სა და Telegram‑ში, AI აგენტები ავსებენ CRM‑ს და ამზადებენ დოკუმენტებს — ქართულად, ინგლისურად და რუსულად. გადაწყვეტილებებს თქვენი გუნდი იღებს.'),
  heroSecondary:c('Посмотреть, как это работает','See it in action','ნახეთ, როგორ მუშაობს'),
  demoTitle:c('ЗАЯВКА → ПРЕДЛОЖЕНИЕ','ENQUIRY → PROPOSAL','მოთხოვნა → შეთავაზება'),
  demoMsg:c('Привет, надо 30 стульев на завтра в Батуми, скиньте прайс','Hi, we need 30 chairs in Batumi tomorrow. Can you send prices?','გამარჯობა, ხვალ ბათუმში 30 სკამი გვჭირდება. გამოგვიგზავნეთ ფასები.'),
  demoCap0:c('Обычное сообщение. Данные ещё не структурированы.','An everyday message. The details are not structured yet.','ჩვეულებრივი შეტყობინება. მონაცემები ჯერ არ არის სტრუქტურირებული.'),
  demoFoot:c('Демо-сценарий · не реальная отправка','Illustrative demo · no messages sent','დემო სცენარი · შეტყობინება არ იგზავნება'),
  demoRequest:c('Запрос','Request','მოთხოვნა'),demoResult:c('Результат','Result','შედეგი'),
  play:c('Продолжить','Play','გაგრძელება'),pause:c('Пауза','Pause','პაუზა'),
  typing:c('печатает…','typing…','წერს…'),online:c('в сети','online','ონლაინ'),today:c('Сегодня','Today','დღეს'),
  home:c('Главная','Home','მთავარი'),
  detailNote:c('Начнём с одного процесса и измеримого пилота.','Start with one workflow and a measurable pilot.','დავიწყოთ ერთი პროცესითა და გაზომვადი პილოტით.'),
  showResult:c('Показать результат','Show the result','შედეგის ნახვა'),
  nextReview:c('Следующий шаг — проверка сотрудником','Next: staff review','შემდეგ: თანამშრომლის შემოწმება'),
  mockDisclaimer:c('Иллюстрация сценария. Данные условные.','Illustrative workflow. Sample data.','სცენარის ილუსტრაცია. მონაცემები პირობითია.'),
  mockTabs:[c('Входящий запрос','Incoming request','შემოსული მოთხოვნა'),c('Результат обработки','Processed result','დამუშავების შედეგი')],
  resultsH2:c('Польза в рабочем дне.','Value in everyday work.','სარგებელი ყოველდღიურ სამუშაოში.'),
  resultsP:casesVerified?c('Два проекта с разными задачами. Результаты относятся к указанным процессам.','Two projects, different goals. Results apply to the workflows described.','ორი პროექტი, განსხვავებული ამოცანები. შედეგები ეხება აღწერილ პროცესებს.'):c('Два типовых сценария: что делает ассистент и какие показатели мы измеряем. Цифры — ориентиры, реальные значения фиксируем на вашем пилоте.','Two typical scenarios: what the assistant does and which metrics we track. Figures are benchmarks; we record your real numbers in the pilot.','ორი ტიპური სცენარი: რას აკეთებს ასისტენტი და რომელ მაჩვენებლებს ვზომავთ. რიცხვები ორიენტირებია, რეალურ მნიშვნელობებს თქვენს პილოტზე ვაფიქსირებთ.'),
  findWorkflow:c('Найдите свой сценарий.','Find your workflow.','იპოვეთ თქვენი სცენარი.'),
  howEvaluate:c('Как оцениваем результат','How we evaluate results','როგორ ვაფასებთ შედეგს'),
  exploreDept:c('Подробнее для отдела','Explore this department','მეტი განყოფილების შესახებ'),
  useCases:c('Сценарии внедрения','Explore use cases','დანერგვის სცენარები'),
  all12:c('Все 12 отраслей','All 12 industries','ყველა 12 ინდუსტრია'),
  formatsP:c('Можно начать с обучения, настроить готовые инструменты или разработать собственное решение.','Start with training, configure existing tools or build a custom solution.','დაიწყეთ სწავლებით, მზა ინსტრუმენტებით ან საკუთარი გადაწყვეტილებით.'),
  timelineT:c('Сроки','Timeline','ვადები'),
  timeline:c('Точные сроки и стоимость — после бесплатного аудита.','Exact timeline and cost follow a free audit.','ზუსტი ვადა და ღირებულება — უფასო აუდიტის შემდეგ.'),
  whatBuildH2:c('Решения, у которых есть задача.','Solutions with a clear purpose.','გადაწყვეტილებები მკაფიო ამოცანით.'),
  exploreWorkflows:c('Посмотреть сценарии','Explore workflows','სცენარების ნახვა'),
  examplesH2:c('Так это может работать в вашем бизнесе.','How it could work in your business.','როგორ შეიძლება იმუშაოს თქვენს ბიზნესში.'),
  examplesP:c('Три сценария для бизнеса в Грузии: от обращения клиента до следующего действия сотрудника.','Three illustrative scenarios for businesses in Georgia. Explore the workflow and evaluation criteria.','სამი პროექტის სცენარი საქართველოს ბიზნესებისთვის. ნახეთ პროცესი და შეფასების კრიტერიუმები.'),
  illustrative:c('ПРИМЕР РЕШЕНИЯ','ILLUSTRATIVE SOLUTION','გადაწყვეტილების მაგალითი'),
  situation:c('Ситуация','Situation','სიტუაცია'),solution:c('Решение','Solution','გადაწყვეტილება'),measure:c('Что измеряем','What we measure','რას ვზომავთ'),
  exploreScenario:c('Разобрать сценарий','Explore this scenario','სცენარის ნახვა'),
  stackEyebrow:c('Инструменты и интеграции','Tools & integrations','ინსტრუმენტები და ინტეგრაციები'),
  stackP:c('Возможные компоненты решения. Подбор и доступность интеграций проверяем под ваш процесс; названия не означают партнёрство с платформами.','Potential solution components. We check fit and integration availability for your workflow. Names do not imply platform partnerships.','შესაძლო კომპონენტები. ინტეგრაციების ხელმისაწვდომობას ვამოწმებთ თქვენი პროცესისთვის. სახელები არ ნიშნავს პარტნიორობას.'),
  processH2:c('Сначала задача. Потом технология.','The task comes first. Then the technology.','ჯერ ამოცანა. შემდეგ ტექნოლოგია.'),
  processP:c('Договоримся, что считать хорошим результатом, до начала разработки. У каждого этапа — понятный итог.','Agree what success looks like before development starts. Each step has a clear outcome.','შედეგის კრიტერიუმებს შემუშავებამდე ვათანხმებთ. თითოეულ ეტაპს აქვს შედეგი.'),
  trustH2:c('Контроль остаётся у вашего бизнеса.','Control stays with your business.','კონტროლი რჩება თქვენს ბიზნესთან.'),
  logTitle:c('Журнал проверок','Review log','შემოწმების ჟურნალი'),
  whereAI:c('Где ИИ снимает рутину.','Where AI takes on routine work.','სად ამცირებს AI რუტინას.'),
  whereAIP:c('Выберите один процесс для старта. Его можно проверить на ваших документах, диалогах и правилах.','Start with one workflow, tested against your documents, conversations and rules.','დაიწყეთ ერთი პროცესით და შეამოწმეთ თქვენს დოკუმენტებზე, დიალოგებსა და წესებზე.'),
  exploreThis:c('Обсудить сценарий','Discuss this','განვიხილოთ'),
  tested:c('Проверяем на вашей работе.','Tested on your actual work.','ვამოწმებთ თქვენს სამუშაოზე.'),
  sources:c('Источники и интеграции','Sources and integrations','წყაროები და ინტეგრაციები'),
  sourcesNote:c('Проверим доступы и совместимость до оценки проекта.','We check access and compatibility before estimating the project.','პროექტის შეფასებამდე ვამოწმებთ წვდომასა და თავსებადობას.'),
  measureNote:c('Сравниваем с исходным процессом, включая время проверки человеком.','Compare with your baseline, including human review time.','ვადარებთ საწყის პროცესს, ადამიანის შემოწმების დროის ჩათვლით.'),
  dataGuarantee:c('Работаем через корпоративные Enterprise API: ваши данные не используются для обучения публичных моделей. При необходимости разворачиваем решение в вашем контуре — включая поставку GPU-серверов.','We use enterprise APIs: your data is never used to train public models. If needed, we deploy inside your infrastructure — including GPU server supply.','ვმუშაობთ კორპორატიული Enterprise API‑ით: თქვენი მონაცემები არ გამოიყენება საჯარო მოდელების სასწავლად. საჭიროებისას ვნერგავთ თქვენს ინფრასტრუქტურაში — GPU სერვერების მიწოდების ჩათვლით.'),
  oneRole:c('Одна роль. Разные процессы.','One role. Different workflows.','ერთი როლი. სხვადასხვა პროცესი.'),
  industryWorkflows:c('Сценарии для отрасли','Industry workflows','ინდუსტრიის სცენარები'),
  synergyH2:c('Одна система для всех отделов.','One system for every department.','ერთი სისტემა ყველა განყოფილებისთვის.'),
  synergyP:c('Ассистенты отделов работают на общей базе знаний, данных и правилах доступа. Начните с одного отдела — следующий подключается быстрее.','Department assistants share one knowledge base, data and access rules. Start with one team — the next connects faster.','განყოფილებების ასისტენტები იყენებენ საერთო ცოდნის ბაზას, მონაცემებსა და წვდომის წესებს. დაიწყეთ ერთით — შემდეგი უფრო სწრაფად დაემატება.'),
  cmpSupplier:c('Поставщик','Supplier','მომწოდებელი'),cmpPrice:c('Цена','Price','ფასი'),cmpLead:c('Срок','Lead time','ვადა'),cmpTerms:c('Условия','Terms','პირობები'),cmpBest:c('Лучшее','Best','საუკეთესო'),
  faqSub:c('Коротко о цене, сроках, интеграциях и безопасности. Подробнее — на бесплатном аудите.','Short answers on cost, timing, integrations and security. More detail in a free audit.','მოკლედ ფასზე, ვადებზე, ინტეგრაციებსა და უსაფრთხოებაზე. დეტალურად — უფასო აუდიტზე.'),
  faqAskTitle:c('Не нашли ответ?','Didn’t find your answer?','პასუხი ვერ იპოვეთ?'),
  faqAskBody:c('Задайте вопрос напрямую — ответим в течение рабочего дня.','Ask us directly — we reply within one business day.','მოგვწერეთ პირდაპირ — გიპასუხებთ სამუშაო დღის განმავლობაში.'),
  faqAskForm:c('Оставить заявку','Send an enquiry','მოთხოვნა'),
  contactH2:c('Снимите рутину с вашей команды.','Take routine work off your team’s hands.','შეამცირეთ რუტინა თქვენი გუნდისთვის.'),
  contactP:c('Выберите, что отнимает больше всего времени. Покажем, как можно изменить процесс с помощью ИИ.','Choose what takes up the most time. We’ll explore how AI could improve the process.','აირჩიეთ, რა გართმევთ დროს. განვიხილავთ პროცესის გაუმჯობესებას AI‑ით.'),
  contactSteps:[c('Отвечаем по выбранному контакту и уточняем процесс.','We reply via your chosen contact and clarify the workflow.','გიპასუხებთ არჩეული არხით და დავაზუსტებთ პროცესს.'),c('Выбираем одну задачу и критерии пилота.','We pick one task and agree pilot criteria.','ვირჩევთ ერთ ამოცანას და პილოტის კრიტერიუმებს.'),c('Готовим объём работ и расчёт.','We prepare scope and an estimate.','ვამზადებთ სამუშაოს მოცულობასა და შეფასებას.')],
  telegram:c('Написать в Telegram','Message on Telegram','მოგვწერეთ Telegram‑ში'),
  location:c('Грузия · RU / EN / GE','Georgia · EN / GE / RU','საქართველო · GE / EN / RU'),
  whatTakes:c('Где больше всего рутины?','Where is the most routine work?','სად არის ყველაზე მეტი რუტინა?'),
  tellTask:c('Расскажите о задаче','Tell us about your task','მოგვიყევით ამოცანაზე'),
  contextLabel:c('Тема:','Topic:','თემა:'),
  removeContext:c('Убрать контекст','Remove context','კონტექსტის წაშლა'),
  howContact:c('Как с вами связаться?','How should we contact you?','როგორ დაგიკავშირდეთ?'),
  phoneMethod:c('Телефон','Phone','ტელეფონი'),
  phoneLabel:c('Телефон с кодом страны','Phone with country code','ტელეფონი ქვეყნის კოდით'),
  formNote:c('Свяжемся по указанному контакту, уточним процесс и подготовим оценку. Контакт используем только для ответа по заявке.','We’ll contact you, clarify the workflow and prepare an estimate. Your contact is used only to reply to this enquiry.','დაგიკავშირდებით, დავაზუსტებთ პროცესს და მოვამზადებთ შეფასებას. კონტაქტს ვიყენებთ მხოლოდ პასუხისთვის.'),
  submit:c('Получить расчёт проекта','Get a project estimate','მიიღეთ პროექტის შეფასება'),sending:c('Отправляем…','Sending…','იგზავნება…'),
  errorText:c('Не удалось отправить. Попробуйте позже — поля сохранены.','Could not send. Please try later; your entries are preserved.','ვერ გაიგზავნა. სცადეთ მოგვიანებით — მონაცემები შენარჩუნებულია.'),
  invalidText:c('Проверьте контакт: укажите номер с кодом страны или корректное @имя Telegram.','Check your contact: include the country code or a valid Telegram username.','შეამოწმეთ ნომერი ქვეყნის კოდით ან Telegram‑ის სახელი.'),
  successTitle:c('Спасибо! Заявка получена.','Thank you! Enquiry received.','გმადლობთ! მოთხოვნა მიღებულია.'),
  successBody:c('Свяжемся по указанному контакту, уточним процесс и подготовим оценку.','We’ll contact you, clarify the workflow and prepare an estimate.','დაგიკავშირდებით, დავაზუსტებთ პროცესს და მოვამზადებთ შეფასებას.'),
  sendAnother:c('Отправить ещё одну заявку','Send another enquiry','კიდევ ერთი მოთხოვნა'),
  other:c('Другое','Something else','სხვა'),
  footerTag:c('Практический ИИ для реальной работы.','Practical AI for real work.','პრაქტიკული AI რეალური სამუშაოსთვის.'),
  footerAbout:c('Внедрение ИИ в бизнес в Грузии: чат-боты и ИИ-ассистенты для WhatsApp и Telegram, автоматизация CRM и документов, обучение сотрудников.','AI implementation for businesses in Georgia: chatbots and AI assistants for WhatsApp and Telegram, CRM and document automation, team training.','ხელოვნური ინტელექტის დანერგვა ბიზნესში საქართველოში: ჩატბოტები და AI ასისტენტები WhatsApp‑ისა და Telegram‑ისთვის, CRM‑ისა და დოკუმენტების ავტომატიზაცია, გუნდის სწავლება.'),
  footerServices:c('Обучение · внедрение · разработка','Training · implementation · development','სწავლება · დანერგვა · შემუშავება'),
  footerExplore:c('Направления','Explore','მიმართულებები'),
  allIndustries:c('Все отрасли','All industries','ყველა ინდუსტრია'),
 };
}
export type SiteCopy=ReturnType<typeof siteCopy>;
