// Lucide icons used by praxenai.com, by their design names. Kept apart from components/praxen/icon.tsx
// so the praxenai.ge bundle does not grow. Brand glyphs (WhatsApp, Instagram, LinkedIn) come from there.
import type {LucideIcon} from 'lucide-react';
import {AlertCircle,AlertTriangle,ArrowDown,ArrowRight,ArrowRightLeft,ArrowUpRight,BadgeCheck,BarChart3,BedDouble,BellRing,BookOpen,Bot,Briefcase,Calculator,CalendarCheck,CalendarClock,CalendarDays,CalendarPlus,CalendarRange,CalendarX,Check,CheckCircle2,ChevronDown,ChevronLeft,ClipboardCheck,ClipboardList,Clock,Compass,Database,FileEdit,FileSearch,FileSignature,FileText,Flag,GitCompare,Globe,GraduationCap,Hash,Headphones,HelpCircle,Home,Inbox,KeyRound,Landmark,Languages,Layers,LifeBuoy,LineChart,Link,ListChecks,Lock,Mail,Map,MapPin,Megaphone,Menu,MessageCircle,MessageSquareText,MessagesSquare,PackageSearch,Pause,PenLine,Phone,PhoneCall,PhoneForwarded,Play,Plus,Receipt,RefreshCcw,Repeat,Scale,ScrollText,SearchCheck,Settings2,Shield,ShieldCheck,Star,Stethoscope,Table,Tag,ThumbsUp,Ticket,Trash2,TrendingUp,Truck,UserCheck,UserPlus,UserRound,UserSearch,Users,Workflow,Wrench,X} from 'lucide-react';
import {Icon as BrandIcon} from '@/components/praxen/icon';

const icons:Record<string,LucideIcon>={'alert-circle':AlertCircle,'alert-triangle':AlertTriangle,'arrow-down':ArrowDown,'arrow-right':ArrowRight,'arrow-right-left':ArrowRightLeft,'arrow-up-right':ArrowUpRight,'badge-check':BadgeCheck,'bar-chart-3':BarChart3,'bed-double':BedDouble,'bell-ring':BellRing,'book-open':BookOpen,bot:Bot,briefcase:Briefcase,calculator:Calculator,'calendar-check':CalendarCheck,'calendar-clock':CalendarClock,'calendar-days':CalendarDays,'calendar-plus':CalendarPlus,'calendar-range':CalendarRange,'calendar-x':CalendarX,check:Check,'check-circle-2':CheckCircle2,'chevron-down':ChevronDown,'chevron-left':ChevronLeft,'clipboard-check':ClipboardCheck,'clipboard-list':ClipboardList,clock:Clock,compass:Compass,database:Database,'file-edit':FileEdit,'file-search':FileSearch,'file-signature':FileSignature,'file-text':FileText,flag:Flag,'git-compare':GitCompare,globe:Globe,'graduation-cap':GraduationCap,hash:Hash,headphones:Headphones,'help-circle':HelpCircle,home:Home,inbox:Inbox,'key-round':KeyRound,landmark:Landmark,languages:Languages,layers:Layers,'life-buoy':LifeBuoy,'line-chart':LineChart,link:Link,'list-checks':ListChecks,lock:Lock,mail:Mail,map:Map,'map-pin':MapPin,megaphone:Megaphone,menu:Menu,'message-circle':MessageCircle,'message-square-text':MessageSquareText,'messages-square':MessagesSquare,'package-search':PackageSearch,pause:Pause,'pen-line':PenLine,phone:Phone,'phone-call':PhoneCall,'phone-forwarded':PhoneForwarded,play:Play,plus:Plus,receipt:Receipt,'refresh-ccw':RefreshCcw,repeat:Repeat,scale:Scale,'scroll-text':ScrollText,'search-check':SearchCheck,'settings-2':Settings2,shield:Shield,'shield-check':ShieldCheck,star:Star,stethoscope:Stethoscope,table:Table,tag:Tag,'thumbs-up':ThumbsUp,ticket:Ticket,'trash-2':Trash2,'trending-up':TrendingUp,truck:Truck,'user-check':UserCheck,'user-plus':UserPlus,'user-round':UserRound,'user-search':UserSearch,users:Users,workflow:Workflow,wrench:Wrench,x:X};

export function Icon({name,size=24,className,strokeWidth}:{name:string;size?:number;className?:string;strokeWidth?:number}){
 const C=icons[name];
 if(!C)return <BrandIcon name={name} size={size} className={className}/>;
 return <C size={size} strokeWidth={strokeWidth} aria-hidden="true" focusable="false" className={className} style={{display:'block',flexShrink:0}}/>;
}
